// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hGXuZyzubCg89KNadA76kG
// Component: mqxYiv9Fg71Gi
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_new_template_vendure.module.css"; // plasmic-import: hGXuZyzubCg89KNadA76kG/projectcss
import sty from "./PlasmicRequestForItemListPage.module.css"; // plasmic-import: mqxYiv9Fg71Gi/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: 6RtdEvdvixNAMI/icon
import Frame6Icon from "./icons/PlasmicIcon__Frame6"; // plasmic-import: Dd9xfOskzbTivN/icon
import Frame7Icon from "./icons/PlasmicIcon__Frame7"; // plasmic-import: p2GNwuTvHzmKNe/icon
import Frame8Icon from "./icons/PlasmicIcon__Frame8"; // plasmic-import: FNI9-QXSpX_HrN/icon
import Frame9Icon from "./icons/PlasmicIcon__Frame9"; // plasmic-import: zkSQt1vk-MZjmD/icon
import Frame10Icon from "./icons/PlasmicIcon__Frame10"; // plasmic-import: dkJYLT93Q85JOK/icon
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: HKcCIpauuB9CGm/icon
import Frame2Icon from "./icons/PlasmicIcon__Frame2"; // plasmic-import: m4v5BuZET3af0x/icon
import Frame3Icon from "./icons/PlasmicIcon__Frame3"; // plasmic-import: gfo1RJd54zPXVx/icon
import Frame14Icon from "./icons/PlasmicIcon__Frame14"; // plasmic-import: vzeEL8mJIy1vTA/icon

export const PlasmicRequestForItemListPage__VariantProps = new Array();

export const PlasmicRequestForItemListPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicRequestForItemListPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <GraphqlFetcher
            data-plasmic-name={"graphQlFetcher"}
            data-plasmic-override={overrides.graphQlFetcher}
            className={classNames("__wab_instance", sty.graphQlFetcher)}
            dataName={"fetchedData"}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"POST"}
            noLayout={false}
            query={{
              query:
                "query MyQuery($name: String) {\n  characters(filter: {name: $name}) {\n    results {\n      name\n      species\n      image\n    }\n  }\n}\n",
              variables: { name: "Rick Sanchez" }
            }}
            url={"https://rickandmortyapi.com/graphql"}
            varOverrides={{}}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    data-plasmic-name={"nike15"}
                    data-plasmic-override={overrides.nike15}
                    className={classNames(projectcss.all, sty.nike15)}
                  >
                    <div
                      data-plasmic-name={"frame"}
                      data-plasmic-override={overrides.frame}
                      className={classNames(projectcss.all, sty.frame)}
                    >
                      <div
                        data-plasmic-name={"frame2"}
                        data-plasmic-override={overrides.frame2}
                        className={classNames(projectcss.all, sty.frame2)}
                      >
                        <div
                          data-plasmic-name={"placeYourRequest"}
                          data-plasmic-override={overrides.placeYourRequest}
                          className={classNames(
                            projectcss.all,
                            sty.placeYourRequest
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dehRi
                            )}
                          >
                            {"Place your Request"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={
                            "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou"
                          }
                          data-plasmic-override={
                            overrides.justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou
                          }
                          className={classNames(
                            projectcss.all,
                            sty.justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gnlg
                            )}
                          >
                            {
                              "Just tell us what items do you want and we will find the best matches for you."
                            }
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame3"}
                        data-plasmic-override={overrides.frame3}
                        className={classNames(projectcss.all, sty.frame3)}
                      >
                        <div
                          data-plasmic-name={"frame4"}
                          data-plasmic-override={overrides.frame4}
                          className={classNames(projectcss.all, sty.frame4)}
                        >
                          <div
                            data-plasmic-name={"emailAddress"}
                            data-plasmic-override={overrides.emailAddress}
                            className={classNames(
                              projectcss.all,
                              sty.emailAddress
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kIaUl
                              )}
                            >
                              {"Email address"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame5"}
                          data-plasmic-override={overrides.frame5}
                          className={classNames(projectcss.all, sty.frame5)}
                        >
                          <div
                            data-plasmic-name={"firstName"}
                            data-plasmic-override={overrides.firstName}
                            className={classNames(
                              projectcss.all,
                              sty.firstName
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oyWzy
                              )}
                            >
                              {"First Name"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame6"}
                          data-plasmic-override={overrides.frame6}
                          className={classNames(projectcss.all, sty.frame6)}
                        >
                          <div
                            data-plasmic-name={"contactNumber"}
                            data-plasmic-override={overrides.contactNumber}
                            className={classNames(
                              projectcss.all,
                              sty.contactNumber
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mdSra
                              )}
                            >
                              {"contact number"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame7"}
                          data-plasmic-override={overrides.frame7}
                          className={classNames(projectcss.all, sty.frame7)}
                        >
                          <div
                            data-plasmic-name={"whatAreYouLookingFor"}
                            data-plasmic-override={
                              overrides.whatAreYouLookingFor
                            }
                            className={classNames(
                              projectcss.all,
                              sty.whatAreYouLookingFor
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__a7OyA
                              )}
                            >
                              {"What are you looking for?"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame8"}
                          data-plasmic-override={overrides.frame8}
                          className={classNames(projectcss.all, sty.frame8)}
                        >
                          <div
                            data-plasmic-name={"piecesQuantity"}
                            data-plasmic-override={overrides.piecesQuantity}
                            className={classNames(
                              projectcss.all,
                              sty.piecesQuantity
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eYeS
                              )}
                            >
                              {"Pieces ( Quantity )"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame9"}
                            data-plasmic-override={overrides.frame9}
                            className={classNames(projectcss.all, sty.frame9)}
                          />
                        </div>
                        <div
                          data-plasmic-name={"frame10"}
                          data-plasmic-override={overrides.frame10}
                          className={classNames(projectcss.all, sty.frame10)}
                        >
                          <div
                            data-plasmic-name={"frame11"}
                            data-plasmic-override={overrides.frame11}
                            className={classNames(projectcss.all, sty.frame11)}
                          >
                            <div
                              data-plasmic-name={"group"}
                              data-plasmic-override={overrides.group}
                              className={classNames(projectcss.all, sty.group)}
                            >
                              <div
                                data-plasmic-name={"group2"}
                                data-plasmic-override={overrides.group2}
                                className={classNames(
                                  projectcss.all,
                                  sty.group2
                                )}
                              >
                                <div
                                  data-plasmic-name={"group3"}
                                  data-plasmic-override={overrides.group3}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group3
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"group4"}
                                    data-plasmic-override={overrides.group4}
                                    className={classNames(
                                      projectcss.all,
                                      sty.group4
                                    )}
                                  >
                                    <GroupIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__dc3Ib
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"category"}
                            data-plasmic-override={overrides.category}
                            className={classNames(projectcss.all, sty.category)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__liPrr
                              )}
                            >
                              {"Category"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame12"}
                          data-plasmic-override={overrides.frame12}
                          className={classNames(projectcss.all, sty.frame12)}
                        >
                          <div
                            data-plasmic-name={"frame13"}
                            data-plasmic-override={overrides.frame13}
                            className={classNames(projectcss.all, sty.frame13)}
                          >
                            <div
                              data-plasmic-name={"group5"}
                              data-plasmic-override={overrides.group5}
                              className={classNames(projectcss.all, sty.group5)}
                            >
                              <div
                                data-plasmic-name={"group6"}
                                data-plasmic-override={overrides.group6}
                                className={classNames(
                                  projectcss.all,
                                  sty.group6
                                )}
                              >
                                <div
                                  data-plasmic-name={"group7"}
                                  data-plasmic-override={overrides.group7}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group7
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"group8"}
                                    data-plasmic-override={overrides.group8}
                                    className={classNames(
                                      projectcss.all,
                                      sty.group8
                                    )}
                                  >
                                    <GroupIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__uUvLi
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"india"}
                            data-plasmic-override={overrides.india}
                            className={classNames(projectcss.all, sty.india)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uzfyO
                              )}
                            >
                              {"India"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame14"}
                          data-plasmic-override={overrides.frame14}
                          className={classNames(projectcss.all, sty.frame14)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dpT31
                            )}
                          >
                            {"Place Request"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame15"}
                        data-plasmic-override={overrides.frame15}
                        className={classNames(projectcss.all, sty.frame15)}
                      />
                    </div>
                    <div
                      data-plasmic-name={"frame16"}
                      data-plasmic-override={overrides.frame16}
                      className={classNames(projectcss.all, sty.frame16)}
                    >
                      <div
                        data-plasmic-name={"frame17"}
                        data-plasmic-override={overrides.frame17}
                        className={classNames(projectcss.all, sty.frame17)}
                      >
                        <div
                          data-plasmic-name={"frame18"}
                          data-plasmic-override={overrides.frame18}
                          className={classNames(projectcss.all, sty.frame18)}
                        >
                          <div
                            data-plasmic-name={"frame19"}
                            data-plasmic-override={overrides.frame19}
                            className={classNames(projectcss.all, sty.frame19)}
                          >
                            <div
                              data-plasmic-name={"frame20"}
                              data-plasmic-override={overrides.frame20}
                              className={classNames(
                                projectcss.all,
                                sty.frame20
                              )}
                            >
                              <div
                                data-plasmic-name={"frame21"}
                                data-plasmic-override={overrides.frame21}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame21
                                )}
                              >
                                <div
                                  data-plasmic-name={"findAStore"}
                                  data-plasmic-override={overrides.findAStore}
                                  className={classNames(
                                    projectcss.all,
                                    sty.findAStore
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__l11GX
                                    )}
                                  >
                                    {"Find A Store"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"becomeAMember"}
                                  data-plasmic-override={
                                    overrides.becomeAMember
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.becomeAMember
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___3TFav
                                    )}
                                  >
                                    {"Become A Member"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"signUpForEmail"}
                                  data-plasmic-override={
                                    overrides.signUpForEmail
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.signUpForEmail
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__flMgh
                                    )}
                                  >
                                    {"Sign Up for Email"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"sendUsFeedback"}
                                  data-plasmic-override={
                                    overrides.sendUsFeedback
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.sendUsFeedback
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___8Z0Lg
                                    )}
                                  >
                                    {"Send Us Feedback"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"studentDiscounts"}
                                  data-plasmic-override={
                                    overrides.studentDiscounts
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.studentDiscounts
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__nCXbv
                                    )}
                                  >
                                    {"Student Discounts"}
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame22"}
                              data-plasmic-override={overrides.frame22}
                              className={classNames(
                                projectcss.all,
                                sty.frame22
                              )}
                            >
                              <div
                                data-plasmic-name={"frame23"}
                                data-plasmic-override={overrides.frame23}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame23
                                )}
                              >
                                <div
                                  data-plasmic-name={"getHelp"}
                                  data-plasmic-override={overrides.getHelp}
                                  className={classNames(
                                    projectcss.all,
                                    sty.getHelp
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__q9PpO
                                    )}
                                  >
                                    {"Get Help"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"orderStatus"}
                                  data-plasmic-override={overrides.orderStatus}
                                  className={classNames(
                                    projectcss.all,
                                    sty.orderStatus
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__tXigD
                                    )}
                                  >
                                    {"Order Status"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"delivery"}
                                  data-plasmic-override={overrides.delivery}
                                  className={classNames(
                                    projectcss.all,
                                    sty.delivery
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__seu6R
                                    )}
                                  >
                                    {"Delivery"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"returns"}
                                  data-plasmic-override={overrides.returns}
                                  className={classNames(
                                    projectcss.all,
                                    sty.returns
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__bna3V
                                    )}
                                  >
                                    {"Returns"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"paymentOptions"}
                                  data-plasmic-override={
                                    overrides.paymentOptions
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.paymentOptions
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__obJpp
                                    )}
                                  >
                                    {"Payment Options"}
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame24"}
                              data-plasmic-override={overrides.frame24}
                              className={classNames(
                                projectcss.all,
                                sty.frame24
                              )}
                            >
                              <div
                                data-plasmic-name={"frame25"}
                                data-plasmic-override={overrides.frame25}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame25
                                )}
                              >
                                <div
                                  data-plasmic-name={"aboutUs"}
                                  data-plasmic-override={overrides.aboutUs}
                                  className={classNames(
                                    projectcss.all,
                                    sty.aboutUs
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__oHtXz
                                    )}
                                  >
                                    {"About US"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"news"}
                                  data-plasmic-override={overrides.news}
                                  className={classNames(
                                    projectcss.all,
                                    sty.news
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__dMuuM
                                    )}
                                  >
                                    {"News"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"careers"}
                                  data-plasmic-override={overrides.careers}
                                  className={classNames(
                                    projectcss.all,
                                    sty.careers
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___5B60U
                                    )}
                                  >
                                    {"Careers"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"investors"}
                                  data-plasmic-override={overrides.investors}
                                  className={classNames(
                                    projectcss.all,
                                    sty.investors
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__ruoLk
                                    )}
                                  >
                                    {"Investors"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"sustainability"}
                                  data-plasmic-override={
                                    overrides.sustainability
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.sustainability
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__a9Ucx
                                    )}
                                  >
                                    {"Sustainability"}
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame26"}
                            data-plasmic-override={overrides.frame26}
                            className={classNames(projectcss.all, sty.frame26)}
                          >
                            <div
                              data-plasmic-name={"frame27"}
                              data-plasmic-override={overrides.frame27}
                              className={classNames(
                                projectcss.all,
                                sty.frame27
                              )}
                            >
                              <Frame6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__lPUeZ
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              data-plasmic-name={"frame28"}
                              data-plasmic-override={overrides.frame28}
                              className={classNames(
                                projectcss.all,
                                sty.frame28
                              )}
                            >
                              <Frame7Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__sgRb4
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              data-plasmic-name={"frame29"}
                              data-plasmic-override={overrides.frame29}
                              className={classNames(
                                projectcss.all,
                                sty.frame29
                              )}
                            >
                              <Frame8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gsL7K
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              data-plasmic-name={"frame30"}
                              data-plasmic-override={overrides.frame30}
                              className={classNames(
                                projectcss.all,
                                sty.frame30
                              )}
                            >
                              <Frame9Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bSuUn
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame31"}
                          data-plasmic-override={overrides.frame31}
                          className={classNames(projectcss.all, sty.frame31)}
                        >
                          <div
                            data-plasmic-name={"frame32"}
                            data-plasmic-override={overrides.frame32}
                            className={classNames(projectcss.all, sty.frame32)}
                          >
                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"autoLayoutHorizontal"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal
                              )}
                            >
                              <div
                                data-plasmic-name={"frame33"}
                                data-plasmic-override={overrides.frame33}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame33
                                )}
                              >
                                <Frame10Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__duNPr
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__llHpq
                                )}
                              >
                                {"India"}
                              </div>
                            </p.Stack>
                            <div
                              data-plasmic-name={
                                "_2023CompanyIncAllRightsReserved"
                              }
                              data-plasmic-override={
                                overrides._2023CompanyIncAllRightsReserved
                              }
                              className={classNames(
                                projectcss.all,
                                sty._2023CompanyIncAllRightsReserved
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__xnX9Q
                                )}
                              >
                                {"© 2023 Company, Inc. All Rights Reserved"}
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame34"}
                            data-plasmic-override={overrides.frame34}
                            className={classNames(projectcss.all, sty.frame34)}
                          >
                            <div
                              data-plasmic-name={"guides"}
                              data-plasmic-override={overrides.guides}
                              className={classNames(projectcss.all, sty.guides)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__xeQm
                                )}
                              >
                                {"Guides"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"termsOfSale"}
                              data-plasmic-override={overrides.termsOfSale}
                              className={classNames(
                                projectcss.all,
                                sty.termsOfSale
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__obOni
                                )}
                              >
                                {"Terms of Sale"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"termsOfUse"}
                              data-plasmic-override={overrides.termsOfUse}
                              className={classNames(
                                projectcss.all,
                                sty.termsOfUse
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ofYkm
                                )}
                              >
                                {"Terms of Use"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"privacyPolicy"}
                              data-plasmic-override={overrides.privacyPolicy}
                              className={classNames(
                                projectcss.all,
                                sty.privacyPolicy
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__daVaz
                                )}
                              >
                                {"Privacy Policy"}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"frame35"}
                      data-plasmic-override={overrides.frame35}
                      className={classNames(projectcss.all, sty.frame35)}
                    >
                      <div
                        data-plasmic-name={"frame36"}
                        data-plasmic-override={overrides.frame36}
                        className={classNames(projectcss.all, sty.frame36)}
                      >
                        <div
                          data-plasmic-name={"frame37"}
                          data-plasmic-override={overrides.frame37}
                          className={classNames(projectcss.all, sty.frame37)}
                        >
                          <div
                            data-plasmic-name={"frame38"}
                            data-plasmic-override={overrides.frame38}
                            className={classNames(projectcss.all, sty.frame38)}
                          >
                            <div
                              data-plasmic-name={"newFeatured"}
                              data-plasmic-override={overrides.newFeatured}
                              className={classNames(
                                projectcss.all,
                                sty.newFeatured
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___0CiTj
                                )}
                              >
                                {"New & Featured"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"autoLayoutHorizontal2"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal2
                              }
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal2
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___69Uz
                                )}
                              >
                                {"Men"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"women"}
                              data-plasmic-override={overrides.women}
                              className={classNames(projectcss.all, sty.women)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__w0PnV
                                )}
                              >
                                {"Women"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"kids"}
                              data-plasmic-override={overrides.kids}
                              className={classNames(projectcss.all, sty.kids)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7GtIe
                                )}
                              >
                                {"Kids"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"sale"}
                              data-plasmic-override={overrides.sale}
                              className={classNames(projectcss.all, sty.sale)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__gbiHw
                                )}
                              >
                                {"Sale"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"snkrs"}
                              data-plasmic-override={overrides.snkrs}
                              className={classNames(projectcss.all, sty.snkrs)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___8SNhe
                                )}
                              >
                                {"SNKRS"}
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame39"}
                          data-plasmic-override={overrides.frame39}
                          className={classNames(projectcss.all, sty.frame39)}
                        >
                          <div
                            data-plasmic-name={"frame40"}
                            data-plasmic-override={overrides.frame40}
                            className={classNames(projectcss.all, sty.frame40)}
                          >
                            <div
                              data-plasmic-name={"frame41"}
                              data-plasmic-override={overrides.frame41}
                              className={classNames(
                                projectcss.all,
                                sty.frame41
                              )}
                            >
                              <div
                                data-plasmic-name={"frame42"}
                                data-plasmic-override={overrides.frame42}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame42
                                )}
                              >
                                <div
                                  data-plasmic-name={"search"}
                                  data-plasmic-override={overrides.search}
                                  className={classNames(
                                    projectcss.all,
                                    sty.search
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___1VndH
                                    )}
                                  >
                                    {"Search"}
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"autoLayoutHorizontal3"}
                                data-plasmic-override={
                                  overrides.autoLayoutHorizontal3
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.autoLayoutHorizontal3
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame43"}
                                  data-plasmic-override={overrides.frame43}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame43
                                  )}
                                >
                                  <FrameIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__udxAr
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"autoLayoutHorizontal4"}
                            data-plasmic-override={
                              overrides.autoLayoutHorizontal4
                            }
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutHorizontal4
                            )}
                          >
                            <div
                              data-plasmic-name={"autoLayoutHorizontal5"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal5
                              }
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal5
                              )}
                            >
                              <div
                                data-plasmic-name={"frame44"}
                                data-plasmic-override={overrides.frame44}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame44
                                )}
                              >
                                <Frame2Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__tMxcf
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame45"}
                              data-plasmic-override={overrides.frame45}
                              className={classNames(
                                projectcss.all,
                                sty.frame45
                              )}
                            >
                              <div
                                data-plasmic-name={"frame46"}
                                data-plasmic-override={overrides.frame46}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame46
                                )}
                              >
                                <Frame3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__vHwcy
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ynBs
                                )}
                              >
                                {"2"}
                              </div>
                            </div>
                          </p.Stack>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame47"}
                        data-plasmic-override={overrides.frame47}
                        className={classNames(projectcss.all, sty.frame47)}
                      >
                        <div
                          data-plasmic-name={"frame48"}
                          data-plasmic-override={overrides.frame48}
                          className={classNames(projectcss.all, sty.frame48)}
                        >
                          <div
                            data-plasmic-name={"frame49"}
                            data-plasmic-override={overrides.frame49}
                            className={classNames(projectcss.all, sty.frame49)}
                          >
                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"autoLayoutHorizontal6"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal6
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal6
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vm3Nl
                                )}
                              >
                                {"Help"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___6MbBu
                                )}
                              >
                                {"|"}
                              </div>
                            </p.Stack>
                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"autoLayoutHorizontal7"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal7
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal7
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__kk79L
                                )}
                              >
                                {"Hi, Rajarshi"}
                              </div>
                              <div
                                data-plasmic-name={"autoLayoutHorizontal8"}
                                data-plasmic-override={
                                  overrides.autoLayoutHorizontal8
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.autoLayoutHorizontal8
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame50"}
                                  data-plasmic-override={overrides.frame50}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame50
                                  )}
                                >
                                  <Frame14Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__t8PD8
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </p.Stack>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphqlFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "graphQlFetcher",
    "freeBox",
    "nike15",
    "frame",
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou",
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy",
    "frame35",
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  graphQlFetcher: [
    "graphQlFetcher",
    "freeBox",
    "nike15",
    "frame",
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou",
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy",
    "frame35",
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  freeBox: [
    "freeBox",
    "nike15",
    "frame",
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou",
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy",
    "frame35",
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  nike15: [
    "nike15",
    "frame",
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou",
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy",
    "frame35",
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  frame: [
    "frame",
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou",
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14",
    "frame15"
  ],

  frame2: [
    "frame2",
    "placeYourRequest",
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou"
  ],

  placeYourRequest: ["placeYourRequest"],
  justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou: [
    "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou"
  ],

  frame3: [
    "frame3",
    "frame4",
    "emailAddress",
    "frame5",
    "firstName",
    "frame6",
    "contactNumber",
    "frame7",
    "whatAreYouLookingFor",
    "frame8",
    "piecesQuantity",
    "frame9",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category",
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame14"
  ],

  frame4: ["frame4", "emailAddress"],
  emailAddress: ["emailAddress"],
  frame5: ["frame5", "firstName"],
  firstName: ["firstName"],
  frame6: ["frame6", "contactNumber"],
  contactNumber: ["contactNumber"],
  frame7: ["frame7", "whatAreYouLookingFor"],
  whatAreYouLookingFor: ["whatAreYouLookingFor"],
  frame8: ["frame8", "piecesQuantity", "frame9"],
  piecesQuantity: ["piecesQuantity"],
  frame9: ["frame9"],
  frame10: [
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "category"
  ],

  frame11: ["frame11", "group", "group2", "group3", "group4"],
  group: ["group", "group2", "group3", "group4"],
  group2: ["group2", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  category: ["category"],
  frame12: [
    "frame12",
    "frame13",
    "group5",
    "group6",
    "group7",
    "group8",
    "india"
  ],

  frame13: ["frame13", "group5", "group6", "group7", "group8"],
  group5: ["group5", "group6", "group7", "group8"],
  group6: ["group6", "group7", "group8"],
  group7: ["group7", "group8"],
  group8: ["group8"],
  india: ["india"],
  frame14: ["frame14"],
  frame15: ["frame15"],
  frame16: [
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy"
  ],

  frame17: [
    "frame17",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy"
  ],

  frame18: [
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30"
  ],

  frame19: [
    "frame19",
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame20: [
    "frame20",
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  frame21: [
    "frame21",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  findAStore: ["findAStore"],
  becomeAMember: ["becomeAMember"],
  signUpForEmail: ["signUpForEmail"],
  sendUsFeedback: ["sendUsFeedback"],
  studentDiscounts: ["studentDiscounts"],
  frame22: [
    "frame22",
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions"
  ],

  frame23: [
    "frame23",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions"
  ],

  getHelp: ["getHelp"],
  orderStatus: ["orderStatus"],
  delivery: ["delivery"],
  returns: ["returns"],
  paymentOptions: ["paymentOptions"],
  frame24: [
    "frame24",
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame25: [
    "frame25",
    "aboutUs",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  aboutUs: ["aboutUs"],
  news: ["news"],
  careers: ["careers"],
  investors: ["investors"],
  sustainability: ["sustainability"],
  frame26: ["frame26", "frame27", "frame28", "frame29", "frame30"],
  frame27: ["frame27"],
  frame28: ["frame28"],
  frame29: ["frame29"],
  frame30: ["frame30"],
  frame31: [
    "frame31",
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved",
    "frame34",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "privacyPolicy"
  ],

  frame32: [
    "frame32",
    "autoLayoutHorizontal",
    "frame33",
    "_2023CompanyIncAllRightsReserved"
  ],

  autoLayoutHorizontal: ["autoLayoutHorizontal", "frame33"],
  frame33: ["frame33"],
  _2023CompanyIncAllRightsReserved: ["_2023CompanyIncAllRightsReserved"],
  frame34: ["frame34", "guides", "termsOfSale", "termsOfUse", "privacyPolicy"],
  guides: ["guides"],
  termsOfSale: ["termsOfSale"],
  termsOfUse: ["termsOfUse"],
  privacyPolicy: ["privacyPolicy"],
  frame35: [
    "frame35",
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  frame36: [
    "frame36",
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46"
  ],

  frame37: [
    "frame37",
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs"
  ],

  frame38: [
    "frame38",
    "newFeatured",
    "autoLayoutHorizontal2",
    "women",
    "kids",
    "sale",
    "snkrs"
  ],

  newFeatured: ["newFeatured"],
  autoLayoutHorizontal2: ["autoLayoutHorizontal2"],
  women: ["women"],
  kids: ["kids"],
  sale: ["sale"],
  snkrs: ["snkrs"],
  frame39: [
    "frame39",
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43",
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46"
  ],

  frame40: [
    "frame40",
    "frame41",
    "frame42",
    "search",
    "autoLayoutHorizontal3",
    "frame43"
  ],

  frame41: ["frame41", "frame42", "search", "autoLayoutHorizontal3", "frame43"],
  frame42: ["frame42", "search"],
  search: ["search"],
  autoLayoutHorizontal3: ["autoLayoutHorizontal3", "frame43"],
  frame43: ["frame43"],
  autoLayoutHorizontal4: [
    "autoLayoutHorizontal4",
    "autoLayoutHorizontal5",
    "frame44",
    "frame45",
    "frame46"
  ],

  autoLayoutHorizontal5: ["autoLayoutHorizontal5", "frame44"],
  frame44: ["frame44"],
  frame45: ["frame45", "frame46"],
  frame46: ["frame46"],
  frame47: [
    "frame47",
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  frame48: [
    "frame48",
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  frame49: [
    "frame49",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  autoLayoutHorizontal6: ["autoLayoutHorizontal6"],
  autoLayoutHorizontal7: [
    "autoLayoutHorizontal7",
    "autoLayoutHorizontal8",
    "frame50"
  ],

  autoLayoutHorizontal8: ["autoLayoutHorizontal8", "frame50"],
  frame50: ["frame50"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRequestForItemListPage__ArgProps,
          internalVariantPropNames: PlasmicRequestForItemListPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRequestForItemListPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRequestForItemListPage";
  } else {
    func.displayName = `PlasmicRequestForItemListPage.${nodeName}`;
  }
  return func;
}

export const PlasmicRequestForItemListPage = Object.assign(
  // Top-level PlasmicRequestForItemListPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    nike15: makeNodeComponent("nike15"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    placeYourRequest: makeNodeComponent("placeYourRequest"),
    justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou:
      makeNodeComponent(
        "justTellUsWhatItemsDoYouWantAndWeWillFindTheBestMatchesForYou"
      ),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    emailAddress: makeNodeComponent("emailAddress"),
    frame5: makeNodeComponent("frame5"),
    firstName: makeNodeComponent("firstName"),
    frame6: makeNodeComponent("frame6"),
    contactNumber: makeNodeComponent("contactNumber"),
    frame7: makeNodeComponent("frame7"),
    whatAreYouLookingFor: makeNodeComponent("whatAreYouLookingFor"),
    frame8: makeNodeComponent("frame8"),
    piecesQuantity: makeNodeComponent("piecesQuantity"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    frame11: makeNodeComponent("frame11"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    category: makeNodeComponent("category"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    group5: makeNodeComponent("group5"),
    group6: makeNodeComponent("group6"),
    group7: makeNodeComponent("group7"),
    group8: makeNodeComponent("group8"),
    india: makeNodeComponent("india"),
    frame14: makeNodeComponent("frame14"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    frame18: makeNodeComponent("frame18"),
    frame19: makeNodeComponent("frame19"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    findAStore: makeNodeComponent("findAStore"),
    becomeAMember: makeNodeComponent("becomeAMember"),
    signUpForEmail: makeNodeComponent("signUpForEmail"),
    sendUsFeedback: makeNodeComponent("sendUsFeedback"),
    studentDiscounts: makeNodeComponent("studentDiscounts"),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    getHelp: makeNodeComponent("getHelp"),
    orderStatus: makeNodeComponent("orderStatus"),
    delivery: makeNodeComponent("delivery"),
    returns: makeNodeComponent("returns"),
    paymentOptions: makeNodeComponent("paymentOptions"),
    frame24: makeNodeComponent("frame24"),
    frame25: makeNodeComponent("frame25"),
    aboutUs: makeNodeComponent("aboutUs"),
    news: makeNodeComponent("news"),
    careers: makeNodeComponent("careers"),
    investors: makeNodeComponent("investors"),
    sustainability: makeNodeComponent("sustainability"),
    frame26: makeNodeComponent("frame26"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    frame29: makeNodeComponent("frame29"),
    frame30: makeNodeComponent("frame30"),
    frame31: makeNodeComponent("frame31"),
    frame32: makeNodeComponent("frame32"),
    autoLayoutHorizontal: makeNodeComponent("autoLayoutHorizontal"),
    frame33: makeNodeComponent("frame33"),
    _2023CompanyIncAllRightsReserved: makeNodeComponent(
      "_2023CompanyIncAllRightsReserved"
    ),
    frame34: makeNodeComponent("frame34"),
    guides: makeNodeComponent("guides"),
    termsOfSale: makeNodeComponent("termsOfSale"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    privacyPolicy: makeNodeComponent("privacyPolicy"),
    frame35: makeNodeComponent("frame35"),
    frame36: makeNodeComponent("frame36"),
    frame37: makeNodeComponent("frame37"),
    frame38: makeNodeComponent("frame38"),
    newFeatured: makeNodeComponent("newFeatured"),
    autoLayoutHorizontal2: makeNodeComponent("autoLayoutHorizontal2"),
    women: makeNodeComponent("women"),
    kids: makeNodeComponent("kids"),
    sale: makeNodeComponent("sale"),
    snkrs: makeNodeComponent("snkrs"),
    frame39: makeNodeComponent("frame39"),
    frame40: makeNodeComponent("frame40"),
    frame41: makeNodeComponent("frame41"),
    frame42: makeNodeComponent("frame42"),
    search: makeNodeComponent("search"),
    autoLayoutHorizontal3: makeNodeComponent("autoLayoutHorizontal3"),
    frame43: makeNodeComponent("frame43"),
    autoLayoutHorizontal4: makeNodeComponent("autoLayoutHorizontal4"),
    autoLayoutHorizontal5: makeNodeComponent("autoLayoutHorizontal5"),
    frame44: makeNodeComponent("frame44"),
    frame45: makeNodeComponent("frame45"),
    frame46: makeNodeComponent("frame46"),
    frame47: makeNodeComponent("frame47"),
    frame48: makeNodeComponent("frame48"),
    frame49: makeNodeComponent("frame49"),
    autoLayoutHorizontal6: makeNodeComponent("autoLayoutHorizontal6"),
    autoLayoutHorizontal7: makeNodeComponent("autoLayoutHorizontal7"),
    autoLayoutHorizontal8: makeNodeComponent("autoLayoutHorizontal8"),
    frame50: makeNodeComponent("frame50"),
    // Metadata about props expected for PlasmicRequestForItemListPage
    internalVariantProps: PlasmicRequestForItemListPage__VariantProps,
    internalArgProps: PlasmicRequestForItemListPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRequestForItemListPage;
/* prettier-ignore-end */
