// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hGXuZyzubCg89KNadA76kG
// Component: MhXCOvYMrxM6tn
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_new_template_vendure.module.css"; // plasmic-import: hGXuZyzubCg89KNadA76kG/projectcss
import sty from "./PlasmicEditAccount.module.css"; // plasmic-import: MhXCOvYMrxM6tn/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: 6RtdEvdvixNAMI/icon
import Frame6Icon from "./icons/PlasmicIcon__Frame6"; // plasmic-import: Dd9xfOskzbTivN/icon
import Frame7Icon from "./icons/PlasmicIcon__Frame7"; // plasmic-import: p2GNwuTvHzmKNe/icon
import Frame8Icon from "./icons/PlasmicIcon__Frame8"; // plasmic-import: FNI9-QXSpX_HrN/icon
import Frame9Icon from "./icons/PlasmicIcon__Frame9"; // plasmic-import: zkSQt1vk-MZjmD/icon
import Frame10Icon from "./icons/PlasmicIcon__Frame10"; // plasmic-import: dkJYLT93Q85JOK/icon

export const PlasmicEditAccount__VariantProps = new Array();

export const PlasmicEditAccount__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicEditAccount__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <GraphqlFetcher
            data-plasmic-name={"graphQlFetcher"}
            data-plasmic-override={overrides.graphQlFetcher}
            className={classNames("__wab_instance", sty.graphQlFetcher)}
            dataName={"fetchedData"}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"POST"}
            noLayout={false}
            query={{
              query:
                "query MyQuery($name: String) {\n  characters(filter: {name: $name}) {\n    results {\n      name\n      species\n      image\n    }\n  }\n}\n",
              variables: { name: "Rick Sanchez" }
            }}
            url={"https://rickandmortyapi.com/graphql"}
            varOverrides={{}}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    data-plasmic-name={"editAccoutnPage"}
                    data-plasmic-override={overrides.editAccoutnPage}
                    className={classNames(projectcss.all, sty.editAccoutnPage)}
                  >
                    <div
                      data-plasmic-name={"frame"}
                      data-plasmic-override={overrides.frame}
                      className={classNames(projectcss.all, sty.frame)}
                    >
                      <div
                        data-plasmic-name={"frame2"}
                        data-plasmic-override={overrides.frame2}
                        className={classNames(projectcss.all, sty.frame2)}
                      >
                        <div
                          data-plasmic-name={"image"}
                          data-plasmic-override={overrides.image}
                          className={classNames(projectcss.all, sty.image)}
                        />

                        <div
                          data-plasmic-name={"accountEdit"}
                          data-plasmic-override={overrides.accountEdit}
                          className={classNames(
                            projectcss.all,
                            sty.accountEdit
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lumeQ
                            )}
                          >
                            {"Account Edit"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame3"}
                        data-plasmic-override={overrides.frame3}
                        className={classNames(projectcss.all, sty.frame3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v5Fl
                          )}
                        >
                          {"Update"}
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"frame4"}
                      data-plasmic-override={overrides.frame4}
                      className={classNames(projectcss.all, sty.frame4)}
                    >
                      <div
                        data-plasmic-name={"frame5"}
                        data-plasmic-override={overrides.frame5}
                        className={classNames(projectcss.all, sty.frame5)}
                      />

                      <div
                        data-plasmic-name={"frame6"}
                        data-plasmic-override={overrides.frame6}
                        className={classNames(projectcss.all, sty.frame6)}
                      >
                        <div
                          data-plasmic-name={"emailAddress"}
                          data-plasmic-override={overrides.emailAddress}
                          className={classNames(
                            projectcss.all,
                            sty.emailAddress
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ztrnK
                            )}
                          >
                            {"Email address"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame7"}
                        data-plasmic-override={overrides.frame7}
                        className={classNames(projectcss.all, sty.frame7)}
                      >
                        <div
                          data-plasmic-name={"firstName"}
                          data-plasmic-override={overrides.firstName}
                          className={classNames(projectcss.all, sty.firstName)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7SOge
                            )}
                          >
                            {"First Name"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame8"}
                        data-plasmic-override={overrides.frame8}
                        className={classNames(projectcss.all, sty.frame8)}
                      >
                        <div
                          data-plasmic-name={"lastName"}
                          data-plasmic-override={overrides.lastName}
                          className={classNames(projectcss.all, sty.lastName)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__si6Pl
                            )}
                          >
                            {"Last Name"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame9"}
                        data-plasmic-override={overrides.frame9}
                        className={classNames(projectcss.all, sty.frame9)}
                      >
                        <div
                          data-plasmic-name={"mobileNumber"}
                          data-plasmic-override={overrides.mobileNumber}
                          className={classNames(
                            projectcss.all,
                            sty.mobileNumber
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ricyf
                            )}
                          >
                            {"Mobile Number"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame10"}
                        data-plasmic-override={overrides.frame10}
                        className={classNames(projectcss.all, sty.frame10)}
                      >
                        <div
                          data-plasmic-name={"frame11"}
                          data-plasmic-override={overrides.frame11}
                          className={classNames(projectcss.all, sty.frame11)}
                        >
                          <div
                            data-plasmic-name={"group"}
                            data-plasmic-override={overrides.group}
                            className={classNames(projectcss.all, sty.group)}
                          >
                            <div
                              data-plasmic-name={"group2"}
                              data-plasmic-override={overrides.group2}
                              className={classNames(projectcss.all, sty.group2)}
                            >
                              <div
                                data-plasmic-name={"group3"}
                                data-plasmic-override={overrides.group3}
                                className={classNames(
                                  projectcss.all,
                                  sty.group3
                                )}
                              >
                                <div
                                  data-plasmic-name={"group4"}
                                  data-plasmic-override={overrides.group4}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group4
                                  )}
                                >
                                  <GroupIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__yVqXa
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"india"}
                          data-plasmic-override={overrides.india}
                          className={classNames(projectcss.all, sty.india)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tTyIu
                            )}
                          >
                            {"India"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame12"}
                        data-plasmic-override={overrides.frame12}
                        className={classNames(projectcss.all, sty.frame12)}
                      >
                        <div
                          data-plasmic-name={"frame13"}
                          data-plasmic-override={overrides.frame13}
                          className={classNames(projectcss.all, sty.frame13)}
                        >
                          <div
                            data-plasmic-name={"rectangle"}
                            data-plasmic-override={overrides.rectangle}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle
                            )}
                          />

                          <div
                            data-plasmic-name={"male"}
                            data-plasmic-override={overrides.male}
                            className={classNames(projectcss.all, sty.male)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2Du8
                              )}
                            >
                              {"Male"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame14"}
                          data-plasmic-override={overrides.frame14}
                          className={classNames(projectcss.all, sty.frame14)}
                        >
                          <div
                            data-plasmic-name={"rectangle2"}
                            data-plasmic-override={overrides.rectangle2}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle2
                            )}
                          />

                          <div
                            data-plasmic-name={"female"}
                            data-plasmic-override={overrides.female}
                            className={classNames(projectcss.all, sty.female)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bNe1
                              )}
                            >
                              {"Female"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"frame15"}
                      data-plasmic-override={overrides.frame15}
                      className={classNames(projectcss.all, sty.frame15)}
                    >
                      <div
                        data-plasmic-name={"frame16"}
                        data-plasmic-override={overrides.frame16}
                        className={classNames(projectcss.all, sty.frame16)}
                      >
                        <div
                          data-plasmic-name={"frame17"}
                          data-plasmic-override={overrides.frame17}
                          className={classNames(projectcss.all, sty.frame17)}
                        >
                          <div
                            data-plasmic-name={"frame18"}
                            data-plasmic-override={overrides.frame18}
                            className={classNames(projectcss.all, sty.frame18)}
                          >
                            <div
                              data-plasmic-name={"frame19"}
                              data-plasmic-override={overrides.frame19}
                              className={classNames(
                                projectcss.all,
                                sty.frame19
                              )}
                            >
                              <div
                                data-plasmic-name={"findAStore"}
                                data-plasmic-override={overrides.findAStore}
                                className={classNames(
                                  projectcss.all,
                                  sty.findAStore
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__aed63
                                  )}
                                >
                                  {"Find A Store"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"becomeAMember"}
                                data-plasmic-override={overrides.becomeAMember}
                                className={classNames(
                                  projectcss.all,
                                  sty.becomeAMember
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___3JczK
                                  )}
                                >
                                  {"Become A Member"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"signUpForEmail"}
                                data-plasmic-override={overrides.signUpForEmail}
                                className={classNames(
                                  projectcss.all,
                                  sty.signUpForEmail
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__r1Ej0
                                  )}
                                >
                                  {"Sign Up for Email"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"sendUsFeedback"}
                                data-plasmic-override={overrides.sendUsFeedback}
                                className={classNames(
                                  projectcss.all,
                                  sty.sendUsFeedback
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__zNJgP
                                  )}
                                >
                                  {"Send Us Feedback"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"studentDiscounts"}
                                data-plasmic-override={
                                  overrides.studentDiscounts
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.studentDiscounts
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__mIumO
                                  )}
                                >
                                  {"Student Discounts"}
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame20"}
                            data-plasmic-override={overrides.frame20}
                            className={classNames(projectcss.all, sty.frame20)}
                          >
                            <div
                              data-plasmic-name={"frame21"}
                              data-plasmic-override={overrides.frame21}
                              className={classNames(
                                projectcss.all,
                                sty.frame21
                              )}
                            >
                              <div
                                data-plasmic-name={"getHelp"}
                                data-plasmic-override={overrides.getHelp}
                                className={classNames(
                                  projectcss.all,
                                  sty.getHelp
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___53KeF
                                  )}
                                >
                                  {"Get Help"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"orderStatus"}
                                data-plasmic-override={overrides.orderStatus}
                                className={classNames(
                                  projectcss.all,
                                  sty.orderStatus
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__a7B3F
                                  )}
                                >
                                  {"Order Status"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"delivery"}
                                data-plasmic-override={overrides.delivery}
                                className={classNames(
                                  projectcss.all,
                                  sty.delivery
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___7BKIs
                                  )}
                                >
                                  {"Delivery"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"returns"}
                                data-plasmic-override={overrides.returns}
                                className={classNames(
                                  projectcss.all,
                                  sty.returns
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__dM285
                                  )}
                                >
                                  {"Returns"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"paymentOptions"}
                                data-plasmic-override={overrides.paymentOptions}
                                className={classNames(
                                  projectcss.all,
                                  sty.paymentOptions
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__d6LN
                                  )}
                                >
                                  {"Payment Options"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={
                                  "contactUsOnNikecomInquiries"
                                }
                                data-plasmic-override={
                                  overrides.contactUsOnNikecomInquiries
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.contactUsOnNikecomInquiries
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jLrnF
                                  )}
                                >
                                  {"Contact Us On Nike.com Inquiries"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={
                                  "contactUsOnAllOtherInquiries"
                                }
                                data-plasmic-override={
                                  overrides.contactUsOnAllOtherInquiries
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.contactUsOnAllOtherInquiries
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___4Gfnt
                                  )}
                                >
                                  {"Contact Us On All Other Inquiries"}
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame22"}
                            data-plasmic-override={overrides.frame22}
                            className={classNames(projectcss.all, sty.frame22)}
                          >
                            <div
                              data-plasmic-name={"frame23"}
                              data-plasmic-override={overrides.frame23}
                              className={classNames(
                                projectcss.all,
                                sty.frame23
                              )}
                            >
                              <div
                                data-plasmic-name={"aboutNike"}
                                data-plasmic-override={overrides.aboutNike}
                                className={classNames(
                                  projectcss.all,
                                  sty.aboutNike
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___9Enw8
                                  )}
                                >
                                  {"About Nike"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"news"}
                                data-plasmic-override={overrides.news}
                                className={classNames(projectcss.all, sty.news)}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__boccO
                                  )}
                                >
                                  {"News"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"careers"}
                                data-plasmic-override={overrides.careers}
                                className={classNames(
                                  projectcss.all,
                                  sty.careers
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__e4GqM
                                  )}
                                >
                                  {"Careers"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"investors"}
                                data-plasmic-override={overrides.investors}
                                className={classNames(
                                  projectcss.all,
                                  sty.investors
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__o0Jz3
                                  )}
                                >
                                  {"Investors"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"sustainability"}
                                data-plasmic-override={overrides.sustainability}
                                className={classNames(
                                  projectcss.all,
                                  sty.sustainability
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___1Ps9L
                                  )}
                                >
                                  {"Sustainability"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame24"}
                          data-plasmic-override={overrides.frame24}
                          className={classNames(projectcss.all, sty.frame24)}
                        >
                          <div
                            data-plasmic-name={"frame25"}
                            data-plasmic-override={overrides.frame25}
                            className={classNames(projectcss.all, sty.frame25)}
                          >
                            <Frame6Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__nWcHx
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame26"}
                            data-plasmic-override={overrides.frame26}
                            className={classNames(projectcss.all, sty.frame26)}
                          >
                            <Frame7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__dx8Ke
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame27"}
                            data-plasmic-override={overrides.frame27}
                            className={classNames(projectcss.all, sty.frame27)}
                          >
                            <Frame8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__tlXbl
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame28"}
                            data-plasmic-override={overrides.frame28}
                            className={classNames(projectcss.all, sty.frame28)}
                          >
                            <Frame9Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vrGo
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame29"}
                        data-plasmic-override={overrides.frame29}
                        className={classNames(projectcss.all, sty.frame29)}
                      >
                        <div
                          data-plasmic-name={"frame30"}
                          data-plasmic-override={overrides.frame30}
                          className={classNames(projectcss.all, sty.frame30)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"autoLayoutHorizontal"}
                            data-plasmic-override={
                              overrides.autoLayoutHorizontal
                            }
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutHorizontal
                            )}
                          >
                            <div
                              data-plasmic-name={"frame31"}
                              data-plasmic-override={overrides.frame31}
                              className={classNames(
                                projectcss.all,
                                sty.frame31
                              )}
                            >
                              <Frame10Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ubz43
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sgGBl
                              )}
                            >
                              {"India"}
                            </div>
                          </p.Stack>
                          <div
                            data-plasmic-name={"_2023NikeIncAllRightsReserved"}
                            data-plasmic-override={
                              overrides._2023NikeIncAllRightsReserved
                            }
                            className={classNames(
                              projectcss.all,
                              sty._2023NikeIncAllRightsReserved
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__cN2SC
                              )}
                            >
                              {"© 2023 Nike, Inc. All Rights Reserved"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame32"}
                          data-plasmic-override={overrides.frame32}
                          className={classNames(projectcss.all, sty.frame32)}
                        >
                          <div
                            data-plasmic-name={"guides"}
                            data-plasmic-override={overrides.guides}
                            className={classNames(projectcss.all, sty.guides)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hoh09
                              )}
                            >
                              {"Guides"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"termsOfSale"}
                            data-plasmic-override={overrides.termsOfSale}
                            className={classNames(
                              projectcss.all,
                              sty.termsOfSale
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__k87Xp
                              )}
                            >
                              {"Terms of Sale"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"termsOfUse"}
                            data-plasmic-override={overrides.termsOfUse}
                            className={classNames(
                              projectcss.all,
                              sty.termsOfUse
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__l1HC
                              )}
                            >
                              {"Terms of Use"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"nikePrivacyPolicy"}
                            data-plasmic-override={overrides.nikePrivacyPolicy}
                            className={classNames(
                              projectcss.all,
                              sty.nikePrivacyPolicy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__rtQv9
                              )}
                            >
                              {"Nike Privacy Policy"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphqlFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "graphQlFetcher",
    "freeBox",
    "editAccoutnPage",
    "frame",
    "frame2",
    "image",
    "accountEdit",
    "frame3",
    "frame4",
    "frame5",
    "frame6",
    "emailAddress",
    "frame7",
    "firstName",
    "frame8",
    "lastName",
    "frame9",
    "mobileNumber",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india",
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  graphQlFetcher: [
    "graphQlFetcher",
    "freeBox",
    "editAccoutnPage",
    "frame",
    "frame2",
    "image",
    "accountEdit",
    "frame3",
    "frame4",
    "frame5",
    "frame6",
    "emailAddress",
    "frame7",
    "firstName",
    "frame8",
    "lastName",
    "frame9",
    "mobileNumber",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india",
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  freeBox: [
    "freeBox",
    "editAccoutnPage",
    "frame",
    "frame2",
    "image",
    "accountEdit",
    "frame3",
    "frame4",
    "frame5",
    "frame6",
    "emailAddress",
    "frame7",
    "firstName",
    "frame8",
    "lastName",
    "frame9",
    "mobileNumber",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india",
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  editAccoutnPage: [
    "editAccoutnPage",
    "frame",
    "frame2",
    "image",
    "accountEdit",
    "frame3",
    "frame4",
    "frame5",
    "frame6",
    "emailAddress",
    "frame7",
    "firstName",
    "frame8",
    "lastName",
    "frame9",
    "mobileNumber",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india",
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female",
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame: ["frame", "frame2", "image", "accountEdit", "frame3"],
  frame2: ["frame2", "image", "accountEdit"],
  image: ["image"],
  accountEdit: ["accountEdit"],
  frame3: ["frame3"],
  frame4: [
    "frame4",
    "frame5",
    "frame6",
    "emailAddress",
    "frame7",
    "firstName",
    "frame8",
    "lastName",
    "frame9",
    "mobileNumber",
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india",
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female"
  ],

  frame5: ["frame5"],
  frame6: ["frame6", "emailAddress"],
  emailAddress: ["emailAddress"],
  frame7: ["frame7", "firstName"],
  firstName: ["firstName"],
  frame8: ["frame8", "lastName"],
  lastName: ["lastName"],
  frame9: ["frame9", "mobileNumber"],
  mobileNumber: ["mobileNumber"],
  frame10: [
    "frame10",
    "frame11",
    "group",
    "group2",
    "group3",
    "group4",
    "india"
  ],

  frame11: ["frame11", "group", "group2", "group3", "group4"],
  group: ["group", "group2", "group3", "group4"],
  group2: ["group2", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  india: ["india"],
  frame12: [
    "frame12",
    "frame13",
    "rectangle",
    "male",
    "frame14",
    "rectangle2",
    "female"
  ],

  frame13: ["frame13", "rectangle", "male"],
  rectangle: ["rectangle"],
  male: ["male"],
  frame14: ["frame14", "rectangle2", "female"],
  rectangle2: ["rectangle2"],
  female: ["female"],
  frame15: [
    "frame15",
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame16: [
    "frame16",
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "frame28"
  ],

  frame17: [
    "frame17",
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame18: [
    "frame18",
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  frame19: [
    "frame19",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  findAStore: ["findAStore"],
  becomeAMember: ["becomeAMember"],
  signUpForEmail: ["signUpForEmail"],
  sendUsFeedback: ["sendUsFeedback"],
  studentDiscounts: ["studentDiscounts"],
  frame20: [
    "frame20",
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  frame21: [
    "frame21",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  getHelp: ["getHelp"],
  orderStatus: ["orderStatus"],
  delivery: ["delivery"],
  returns: ["returns"],
  paymentOptions: ["paymentOptions"],
  contactUsOnNikecomInquiries: ["contactUsOnNikecomInquiries"],
  contactUsOnAllOtherInquiries: ["contactUsOnAllOtherInquiries"],
  frame22: [
    "frame22",
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame23: [
    "frame23",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  aboutNike: ["aboutNike"],
  news: ["news"],
  careers: ["careers"],
  investors: ["investors"],
  sustainability: ["sustainability"],
  frame24: ["frame24", "frame25", "frame26", "frame27", "frame28"],
  frame25: ["frame25"],
  frame26: ["frame26"],
  frame27: ["frame27"],
  frame28: ["frame28"],
  frame29: [
    "frame29",
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved",
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame30: [
    "frame30",
    "autoLayoutHorizontal",
    "frame31",
    "_2023NikeIncAllRightsReserved"
  ],

  autoLayoutHorizontal: ["autoLayoutHorizontal", "frame31"],
  frame31: ["frame31"],
  _2023NikeIncAllRightsReserved: ["_2023NikeIncAllRightsReserved"],
  frame32: [
    "frame32",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  guides: ["guides"],
  termsOfSale: ["termsOfSale"],
  termsOfUse: ["termsOfUse"],
  nikePrivacyPolicy: ["nikePrivacyPolicy"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicEditAccount__ArgProps,
          internalVariantPropNames: PlasmicEditAccount__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEditAccount__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEditAccount";
  } else {
    func.displayName = `PlasmicEditAccount.${nodeName}`;
  }
  return func;
}

export const PlasmicEditAccount = Object.assign(
  // Top-level PlasmicEditAccount renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    editAccoutnPage: makeNodeComponent("editAccoutnPage"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    image: makeNodeComponent("image"),
    accountEdit: makeNodeComponent("accountEdit"),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    frame6: makeNodeComponent("frame6"),
    emailAddress: makeNodeComponent("emailAddress"),
    frame7: makeNodeComponent("frame7"),
    firstName: makeNodeComponent("firstName"),
    frame8: makeNodeComponent("frame8"),
    lastName: makeNodeComponent("lastName"),
    frame9: makeNodeComponent("frame9"),
    mobileNumber: makeNodeComponent("mobileNumber"),
    frame10: makeNodeComponent("frame10"),
    frame11: makeNodeComponent("frame11"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    india: makeNodeComponent("india"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    rectangle: makeNodeComponent("rectangle"),
    male: makeNodeComponent("male"),
    frame14: makeNodeComponent("frame14"),
    rectangle2: makeNodeComponent("rectangle2"),
    female: makeNodeComponent("female"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    frame18: makeNodeComponent("frame18"),
    frame19: makeNodeComponent("frame19"),
    findAStore: makeNodeComponent("findAStore"),
    becomeAMember: makeNodeComponent("becomeAMember"),
    signUpForEmail: makeNodeComponent("signUpForEmail"),
    sendUsFeedback: makeNodeComponent("sendUsFeedback"),
    studentDiscounts: makeNodeComponent("studentDiscounts"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    getHelp: makeNodeComponent("getHelp"),
    orderStatus: makeNodeComponent("orderStatus"),
    delivery: makeNodeComponent("delivery"),
    returns: makeNodeComponent("returns"),
    paymentOptions: makeNodeComponent("paymentOptions"),
    contactUsOnNikecomInquiries: makeNodeComponent(
      "contactUsOnNikecomInquiries"
    ),
    contactUsOnAllOtherInquiries: makeNodeComponent(
      "contactUsOnAllOtherInquiries"
    ),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    aboutNike: makeNodeComponent("aboutNike"),
    news: makeNodeComponent("news"),
    careers: makeNodeComponent("careers"),
    investors: makeNodeComponent("investors"),
    sustainability: makeNodeComponent("sustainability"),
    frame24: makeNodeComponent("frame24"),
    frame25: makeNodeComponent("frame25"),
    frame26: makeNodeComponent("frame26"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    frame29: makeNodeComponent("frame29"),
    frame30: makeNodeComponent("frame30"),
    autoLayoutHorizontal: makeNodeComponent("autoLayoutHorizontal"),
    frame31: makeNodeComponent("frame31"),
    _2023NikeIncAllRightsReserved: makeNodeComponent(
      "_2023NikeIncAllRightsReserved"
    ),
    frame32: makeNodeComponent("frame32"),
    guides: makeNodeComponent("guides"),
    termsOfSale: makeNodeComponent("termsOfSale"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    nikePrivacyPolicy: makeNodeComponent("nikePrivacyPolicy"),
    // Metadata about props expected for PlasmicEditAccount
    internalVariantProps: PlasmicEditAccount__VariantProps,
    internalArgProps: PlasmicEditAccount__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicEditAccount;
/* prettier-ignore-end */
