// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hGXuZyzubCg89KNadA76kG
// Component: lZVGv9goENe_hd
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_new_template_vendure.module.css"; // plasmic-import: hGXuZyzubCg89KNadA76kG/projectcss
import sty from "./PlasmicAddProducts.module.css"; // plasmic-import: lZVGv9goENe_hd/css
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: xckmqqR_vbI0__/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: FQoq9U1TFPvVRh/icon
import Frame6Icon from "./icons/PlasmicIcon__Frame6"; // plasmic-import: Dd9xfOskzbTivN/icon
import Frame7Icon from "./icons/PlasmicIcon__Frame7"; // plasmic-import: p2GNwuTvHzmKNe/icon
import Frame8Icon from "./icons/PlasmicIcon__Frame8"; // plasmic-import: FNI9-QXSpX_HrN/icon
import Frame9Icon from "./icons/PlasmicIcon__Frame9"; // plasmic-import: zkSQt1vk-MZjmD/icon
import Frame10Icon from "./icons/PlasmicIcon__Frame10"; // plasmic-import: dkJYLT93Q85JOK/icon
import frame41NuZgmTc8QbDtyZ from "./images/frame41.svg"; // plasmic-import: NuZgmTc8qbDtyZ/picture

export const PlasmicAddProducts__VariantProps = new Array();

export const PlasmicAddProducts__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicAddProducts__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <GraphqlFetcher
            data-plasmic-name={"graphQlFetcher"}
            data-plasmic-override={overrides.graphQlFetcher}
            className={classNames("__wab_instance", sty.graphQlFetcher)}
            dataName={"fetchedData"}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"POST"}
            noLayout={false}
            query={{
              query:
                "query MyQuery($name: String) {\n  characters(filter: {name: $name}) {\n    results {\n      name\n      species\n      image\n    }\n  }\n}\n",
              variables: { name: "Rick Sanchez" }
            }}
            url={"https://rickandmortyapi.com/graphql"}
            varOverrides={{}}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    data-plasmic-name={"addProductPage"}
                    data-plasmic-override={overrides.addProductPage}
                    className={classNames(projectcss.all, sty.addProductPage)}
                  >
                    <div
                      data-plasmic-name={"nike18"}
                      data-plasmic-override={overrides.nike18}
                      className={classNames(projectcss.all, sty.nike18)}
                    >
                      <div
                        data-plasmic-name={"frame"}
                        data-plasmic-override={overrides.frame}
                        className={classNames(projectcss.all, sty.frame)}
                      >
                        <div
                          data-plasmic-name={"frame2"}
                          data-plasmic-override={overrides.frame2}
                          className={classNames(projectcss.all, sty.frame2)}
                        >
                          <div
                            data-plasmic-name={"frame3"}
                            data-plasmic-override={overrides.frame3}
                            className={classNames(projectcss.all, sty.frame3)}
                          >
                            <div
                              data-plasmic-name={"group"}
                              data-plasmic-override={overrides.group}
                              className={classNames(projectcss.all, sty.group)}
                            >
                              <div
                                data-plasmic-name={"group2"}
                                data-plasmic-override={overrides.group2}
                                className={classNames(
                                  projectcss.all,
                                  sty.group2
                                )}
                              >
                                <Group2Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__nWFxt
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame4"}
                          data-plasmic-override={overrides.frame4}
                          className={classNames(projectcss.all, sty.frame4)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2TQ3S
                            )}
                          >
                            {"000 800 100 9538"}
                          </div>
                          <div
                            data-plasmic-name={"autoLayoutHorizontal"}
                            data-plasmic-override={
                              overrides.autoLayoutHorizontal
                            }
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutHorizontal
                            )}
                          >
                            <p.PlasmicImg
                              data-plasmic-name={"img"}
                              data-plasmic-override={overrides.img}
                              alt={""}
                              className={classNames(sty.img)}
                              displayHeight={"20px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"20px"}
                              loading={"lazy"}
                              src={{
                                src: frame41NuZgmTc8QbDtyZ,
                                fullWidth: 20,
                                fullHeight: 20,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                          <div
                            data-plasmic-name={"autoLayoutHorizontal2"}
                            data-plasmic-override={
                              overrides.autoLayoutHorizontal2
                            }
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutHorizontal2
                            )}
                          >
                            <div
                              data-plasmic-name={"frame5"}
                              data-plasmic-override={overrides.frame5}
                              className={classNames(projectcss.all, sty.frame5)}
                            >
                              <div
                                data-plasmic-name={"group3"}
                                data-plasmic-override={overrides.group3}
                                className={classNames(
                                  projectcss.all,
                                  sty.group3
                                )}
                              >
                                <div
                                  data-plasmic-name={"group4"}
                                  data-plasmic-override={overrides.group4}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group4
                                  )}
                                >
                                  <Group3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__uDnPe
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame6"}
                        data-plasmic-override={overrides.frame6}
                        className={classNames(projectcss.all, sty.frame6)}
                      >
                        <div
                          data-plasmic-name={"frame7"}
                          data-plasmic-override={overrides.frame7}
                          className={classNames(projectcss.all, sty.frame7)}
                        >
                          <div
                            data-plasmic-name={"frame8"}
                            data-plasmic-override={overrides.frame8}
                            className={classNames(projectcss.all, sty.frame8)}
                          >
                            <div
                              data-plasmic-name={"frame9"}
                              data-plasmic-override={overrides.frame9}
                              className={classNames(projectcss.all, sty.frame9)}
                            >
                              <div
                                data-plasmic-name={"frame10"}
                                data-plasmic-override={overrides.frame10}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame10
                                )}
                              >
                                <div
                                  data-plasmic-name={"addImages"}
                                  data-plasmic-override={overrides.addImages}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.addImages
                                  )}
                                >
                                  {"Add Images : "}
                                </div>
                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"autoLayoutHorizontal3"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal3
                                  }
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal3
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame11"}
                                    data-plasmic-override={overrides.frame11}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame11
                                    )}
                                  />
                                </p.Stack>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame12"}
                          data-plasmic-override={overrides.frame12}
                          className={classNames(projectcss.all, sty.frame12)}
                        >
                          <div
                            data-plasmic-name={"frame13"}
                            data-plasmic-override={overrides.frame13}
                            className={classNames(projectcss.all, sty.frame13)}
                          >
                            <div
                              data-plasmic-name={"frame14"}
                              data-plasmic-override={overrides.frame14}
                              className={classNames(
                                projectcss.all,
                                sty.frame14
                              )}
                            >
                              <div
                                data-plasmic-name={"frame15"}
                                data-plasmic-override={overrides.frame15}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame15
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame16"}
                                  data-plasmic-override={overrides.frame16}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame16
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"findAStore"}
                                    data-plasmic-override={overrides.findAStore}
                                    className={classNames(
                                      projectcss.all,
                                      sty.findAStore
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__onoDw
                                      )}
                                    >
                                      {"Find A Store"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"becomeAMember"}
                                    data-plasmic-override={
                                      overrides.becomeAMember
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.becomeAMember
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__empEp
                                      )}
                                    >
                                      {"Become A Member"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"signUpForEmail"}
                                    data-plasmic-override={
                                      overrides.signUpForEmail
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.signUpForEmail
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___5HkOs
                                      )}
                                    >
                                      {"Sign Up for Email"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"sendUsFeedback"}
                                    data-plasmic-override={
                                      overrides.sendUsFeedback
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.sendUsFeedback
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__kxhIj
                                      )}
                                    >
                                      {"Send Us Feedback"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"studentDiscounts"}
                                    data-plasmic-override={
                                      overrides.studentDiscounts
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.studentDiscounts
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__l7JV6
                                      )}
                                    >
                                      {"Student Discounts"}
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"frame17"}
                                data-plasmic-override={overrides.frame17}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame17
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame18"}
                                  data-plasmic-override={overrides.frame18}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame18
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"getHelp"}
                                    data-plasmic-override={overrides.getHelp}
                                    className={classNames(
                                      projectcss.all,
                                      sty.getHelp
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___338PX
                                      )}
                                    >
                                      {"Get Help"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"orderStatus"}
                                    data-plasmic-override={
                                      overrides.orderStatus
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.orderStatus
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__aHymm
                                      )}
                                    >
                                      {"Order Status"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"delivery"}
                                    data-plasmic-override={overrides.delivery}
                                    className={classNames(
                                      projectcss.all,
                                      sty.delivery
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___3UM1Y
                                      )}
                                    >
                                      {"Delivery"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"returns"}
                                    data-plasmic-override={overrides.returns}
                                    className={classNames(
                                      projectcss.all,
                                      sty.returns
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__jPXg9
                                      )}
                                    >
                                      {"Returns"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"paymentOptions"}
                                    data-plasmic-override={
                                      overrides.paymentOptions
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.paymentOptions
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__hDE
                                      )}
                                    >
                                      {"Payment Options"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={
                                      "contactUsOnNikecomInquiries"
                                    }
                                    data-plasmic-override={
                                      overrides.contactUsOnNikecomInquiries
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.contactUsOnNikecomInquiries
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__v7Waz
                                      )}
                                    >
                                      {"Contact Us On Nike.com Inquiries"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={
                                      "contactUsOnAllOtherInquiries"
                                    }
                                    data-plasmic-override={
                                      overrides.contactUsOnAllOtherInquiries
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.contactUsOnAllOtherInquiries
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___4FpX6
                                      )}
                                    >
                                      {"Contact Us On All Other Inquiries"}
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"frame19"}
                                data-plasmic-override={overrides.frame19}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame19
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame20"}
                                  data-plasmic-override={overrides.frame20}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame20
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"aboutNike"}
                                    data-plasmic-override={overrides.aboutNike}
                                    className={classNames(
                                      projectcss.all,
                                      sty.aboutNike
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___7AtFj
                                      )}
                                    >
                                      {"About Nike"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"news"}
                                    data-plasmic-override={overrides.news}
                                    className={classNames(
                                      projectcss.all,
                                      sty.news
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__xdZp
                                      )}
                                    >
                                      {"News"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"careers"}
                                    data-plasmic-override={overrides.careers}
                                    className={classNames(
                                      projectcss.all,
                                      sty.careers
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___6DvUx
                                      )}
                                    >
                                      {"Careers"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"investors"}
                                    data-plasmic-override={overrides.investors}
                                    className={classNames(
                                      projectcss.all,
                                      sty.investors
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__ltyd2
                                      )}
                                    >
                                      {"Investors"}
                                    </div>
                                  </div>
                                  <div
                                    data-plasmic-name={"sustainability"}
                                    data-plasmic-override={
                                      overrides.sustainability
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.sustainability
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___1Qr1K
                                      )}
                                    >
                                      {"Sustainability"}
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame21"}
                              data-plasmic-override={overrides.frame21}
                              className={classNames(
                                projectcss.all,
                                sty.frame21
                              )}
                            >
                              <div
                                data-plasmic-name={"frame22"}
                                data-plasmic-override={overrides.frame22}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame22
                                )}
                              >
                                <Frame6Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wcmBl
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"frame23"}
                                data-plasmic-override={overrides.frame23}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame23
                                )}
                              >
                                <Frame7Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__lvFIz
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"frame24"}
                                data-plasmic-override={overrides.frame24}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame24
                                )}
                              >
                                <Frame8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__aa2Wz
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"frame25"}
                                data-plasmic-override={overrides.frame25}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame25
                                )}
                              >
                                <Frame9Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__oLpVy
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame26"}
                            data-plasmic-override={overrides.frame26}
                            className={classNames(projectcss.all, sty.frame26)}
                          >
                            <div
                              data-plasmic-name={"frame27"}
                              data-plasmic-override={overrides.frame27}
                              className={classNames(
                                projectcss.all,
                                sty.frame27
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                data-plasmic-name={"autoLayoutHorizontal4"}
                                data-plasmic-override={
                                  overrides.autoLayoutHorizontal4
                                }
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.autoLayoutHorizontal4
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame28"}
                                  data-plasmic-override={overrides.frame28}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame28
                                  )}
                                >
                                  <Frame10Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__h8GJ
                                    )}
                                    role={"img"}
                                  />
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__hpLfT
                                  )}
                                >
                                  {"India"}
                                </div>
                              </p.Stack>
                              <div
                                data-plasmic-name={
                                  "_2023NikeIncAllRightsReserved"
                                }
                                data-plasmic-override={
                                  overrides._2023NikeIncAllRightsReserved
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty._2023NikeIncAllRightsReserved
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__gmT1W
                                  )}
                                >
                                  {"© 2023 Nike, Inc. All Rights Reserved"}
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame29"}
                              data-plasmic-override={overrides.frame29}
                              className={classNames(
                                projectcss.all,
                                sty.frame29
                              )}
                            >
                              <div
                                data-plasmic-name={"guides"}
                                data-plasmic-override={overrides.guides}
                                className={classNames(
                                  projectcss.all,
                                  sty.guides
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__x2N5L
                                  )}
                                >
                                  {"Guides"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"termsOfSale"}
                                data-plasmic-override={overrides.termsOfSale}
                                className={classNames(
                                  projectcss.all,
                                  sty.termsOfSale
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___68QBj
                                  )}
                                >
                                  {"Terms of Sale"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"termsOfUse"}
                                data-plasmic-override={overrides.termsOfUse}
                                className={classNames(
                                  projectcss.all,
                                  sty.termsOfUse
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__tIntb
                                  )}
                                >
                                  {"Terms of Use"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"nikePrivacyPolicy"}
                                data-plasmic-override={
                                  overrides.nikePrivacyPolicy
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.nikePrivacyPolicy
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__aakSw
                                  )}
                                >
                                  {"Nike Privacy Policy"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ihbSn
                        )}
                      >
                        {"Add Product  Images"}
                      </div>
                      <div
                        data-plasmic-name={"autoLayoutVertical"}
                        data-plasmic-override={overrides.autoLayoutVertical}
                        className={classNames(
                          projectcss.all,
                          sty.autoLayoutVertical
                        )}
                      >
                        <div
                          data-plasmic-name={"frame30"}
                          data-plasmic-override={overrides.frame30}
                          className={classNames(projectcss.all, sty.frame30)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"autoLayoutVertical2"}
                            data-plasmic-override={
                              overrides.autoLayoutVertical2
                            }
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutVertical2
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__w3DfT
                              )}
                            >
                              {"Add Product  Title"}
                            </div>
                            <div
                              data-plasmic-name={"autoLayoutVertical3"}
                              data-plasmic-override={
                                overrides.autoLayoutVertical3
                              }
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutVertical3
                              )}
                            >
                              <div
                                data-plasmic-name={"frame31"}
                                data-plasmic-override={overrides.frame31}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame31
                                )}
                              >
                                <div
                                  data-plasmic-name={"autoLayoutHorizontal5"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal5
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal5
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___6Ad4G
                                    )}
                                  >
                                    {"Title"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"frame32"}
                                  data-plasmic-override={overrides.frame32}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame32
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"autoLayoutHorizontal6"}
                                    data-plasmic-override={
                                      overrides.autoLayoutHorizontal6
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.autoLayoutHorizontal6
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__mIXem
                                      )}
                                    >
                                      {"Description"}
                                    </div>
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"autoLayoutHorizontal7"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal7
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal7
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"price"}
                                    data-plasmic-override={overrides.price}
                                    className={classNames(
                                      projectcss.all,
                                      sty.price
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__biZbW
                                      )}
                                    >
                                      {"$ Price"}
                                    </div>
                                  </div>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__uXq4I
                                  )}
                                >
                                  {"Product Description"}
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__kRbLd
                                  )}
                                >
                                  {"Price"}
                                </div>
                                <div
                                  data-plasmic-name={"autoLayoutHorizontal8"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal8
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal8
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"addProduct"}
                                    data-plasmic-override={overrides.addProduct}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.addProduct
                                    )}
                                  >
                                    {"Add Product "}
                                  </div>
                                </div>
                              </div>
                            </div>
                          </p.Stack>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"addProductPage2"}
                        data-plasmic-override={overrides.addProductPage2}
                        className={classNames(
                          projectcss.all,
                          sty.addProductPage2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6Edyz
                          )}
                        >
                          {"Add Product Page"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphqlFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "graphQlFetcher",
    "freeBox",
    "addProductPage",
    "nike18",
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4",
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct",
    "addProductPage2"
  ],

  graphQlFetcher: [
    "graphQlFetcher",
    "freeBox",
    "addProductPage",
    "nike18",
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4",
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct",
    "addProductPage2"
  ],

  freeBox: [
    "freeBox",
    "addProductPage",
    "nike18",
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4",
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct",
    "addProductPage2"
  ],

  addProductPage: [
    "addProductPage",
    "nike18",
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4",
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct",
    "addProductPage2"
  ],

  nike18: [
    "nike18",
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4",
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct",
    "addProductPage2"
  ],

  frame: [
    "frame",
    "frame2",
    "frame3",
    "group",
    "group2",
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4"
  ],

  frame2: ["frame2", "frame3", "group", "group2"],
  frame3: ["frame3", "group", "group2"],
  group: ["group", "group2"],
  group2: ["group2"],
  frame4: [
    "frame4",
    "autoLayoutHorizontal",
    "img",
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4"
  ],

  autoLayoutHorizontal: ["autoLayoutHorizontal", "img"],
  img: ["img"],
  autoLayoutHorizontal2: [
    "autoLayoutHorizontal2",
    "frame5",
    "group3",
    "group4"
  ],

  frame5: ["frame5", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  frame6: [
    "frame6",
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame7: [
    "frame7",
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11"
  ],

  frame8: [
    "frame8",
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11"
  ],

  frame9: [
    "frame9",
    "frame10",
    "addImages",
    "autoLayoutHorizontal3",
    "frame11"
  ],

  frame10: ["frame10", "addImages", "autoLayoutHorizontal3", "frame11"],
  addImages: ["addImages"],
  autoLayoutHorizontal3: ["autoLayoutHorizontal3", "frame11"],
  frame11: ["frame11"],
  frame12: [
    "frame12",
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame13: [
    "frame13",
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25"
  ],

  frame14: [
    "frame14",
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame15: [
    "frame15",
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  frame16: [
    "frame16",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  findAStore: ["findAStore"],
  becomeAMember: ["becomeAMember"],
  signUpForEmail: ["signUpForEmail"],
  sendUsFeedback: ["sendUsFeedback"],
  studentDiscounts: ["studentDiscounts"],
  frame17: [
    "frame17",
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  frame18: [
    "frame18",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  getHelp: ["getHelp"],
  orderStatus: ["orderStatus"],
  delivery: ["delivery"],
  returns: ["returns"],
  paymentOptions: ["paymentOptions"],
  contactUsOnNikecomInquiries: ["contactUsOnNikecomInquiries"],
  contactUsOnAllOtherInquiries: ["contactUsOnAllOtherInquiries"],
  frame19: [
    "frame19",
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame20: [
    "frame20",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  aboutNike: ["aboutNike"],
  news: ["news"],
  careers: ["careers"],
  investors: ["investors"],
  sustainability: ["sustainability"],
  frame21: ["frame21", "frame22", "frame23", "frame24", "frame25"],
  frame22: ["frame22"],
  frame23: ["frame23"],
  frame24: ["frame24"],
  frame25: ["frame25"],
  frame26: [
    "frame26",
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved",
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame27: [
    "frame27",
    "autoLayoutHorizontal4",
    "frame28",
    "_2023NikeIncAllRightsReserved"
  ],

  autoLayoutHorizontal4: ["autoLayoutHorizontal4", "frame28"],
  frame28: ["frame28"],
  _2023NikeIncAllRightsReserved: ["_2023NikeIncAllRightsReserved"],
  frame29: [
    "frame29",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  guides: ["guides"],
  termsOfSale: ["termsOfSale"],
  termsOfUse: ["termsOfUse"],
  nikePrivacyPolicy: ["nikePrivacyPolicy"],
  autoLayoutVertical: [
    "autoLayoutVertical",
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct"
  ],

  frame30: [
    "frame30",
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct"
  ],

  autoLayoutVertical2: [
    "autoLayoutVertical2",
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct"
  ],

  autoLayoutVertical3: [
    "autoLayoutVertical3",
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct"
  ],

  frame31: [
    "frame31",
    "autoLayoutHorizontal5",
    "frame32",
    "autoLayoutHorizontal6",
    "autoLayoutHorizontal7",
    "price",
    "autoLayoutHorizontal8",
    "addProduct"
  ],

  autoLayoutHorizontal5: ["autoLayoutHorizontal5"],
  frame32: ["frame32", "autoLayoutHorizontal6"],
  autoLayoutHorizontal6: ["autoLayoutHorizontal6"],
  autoLayoutHorizontal7: ["autoLayoutHorizontal7", "price"],
  price: ["price"],
  autoLayoutHorizontal8: ["autoLayoutHorizontal8", "addProduct"],
  addProduct: ["addProduct"],
  addProductPage2: ["addProductPage2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAddProducts__ArgProps,
          internalVariantPropNames: PlasmicAddProducts__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAddProducts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAddProducts";
  } else {
    func.displayName = `PlasmicAddProducts.${nodeName}`;
  }
  return func;
}

export const PlasmicAddProducts = Object.assign(
  // Top-level PlasmicAddProducts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    addProductPage: makeNodeComponent("addProductPage"),
    nike18: makeNodeComponent("nike18"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    frame4: makeNodeComponent("frame4"),
    autoLayoutHorizontal: makeNodeComponent("autoLayoutHorizontal"),
    img: makeNodeComponent("img"),
    autoLayoutHorizontal2: makeNodeComponent("autoLayoutHorizontal2"),
    frame5: makeNodeComponent("frame5"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    frame8: makeNodeComponent("frame8"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    addImages: makeNodeComponent("addImages"),
    autoLayoutHorizontal3: makeNodeComponent("autoLayoutHorizontal3"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    frame14: makeNodeComponent("frame14"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    findAStore: makeNodeComponent("findAStore"),
    becomeAMember: makeNodeComponent("becomeAMember"),
    signUpForEmail: makeNodeComponent("signUpForEmail"),
    sendUsFeedback: makeNodeComponent("sendUsFeedback"),
    studentDiscounts: makeNodeComponent("studentDiscounts"),
    frame17: makeNodeComponent("frame17"),
    frame18: makeNodeComponent("frame18"),
    getHelp: makeNodeComponent("getHelp"),
    orderStatus: makeNodeComponent("orderStatus"),
    delivery: makeNodeComponent("delivery"),
    returns: makeNodeComponent("returns"),
    paymentOptions: makeNodeComponent("paymentOptions"),
    contactUsOnNikecomInquiries: makeNodeComponent(
      "contactUsOnNikecomInquiries"
    ),
    contactUsOnAllOtherInquiries: makeNodeComponent(
      "contactUsOnAllOtherInquiries"
    ),
    frame19: makeNodeComponent("frame19"),
    frame20: makeNodeComponent("frame20"),
    aboutNike: makeNodeComponent("aboutNike"),
    news: makeNodeComponent("news"),
    careers: makeNodeComponent("careers"),
    investors: makeNodeComponent("investors"),
    sustainability: makeNodeComponent("sustainability"),
    frame21: makeNodeComponent("frame21"),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    frame25: makeNodeComponent("frame25"),
    frame26: makeNodeComponent("frame26"),
    frame27: makeNodeComponent("frame27"),
    autoLayoutHorizontal4: makeNodeComponent("autoLayoutHorizontal4"),
    frame28: makeNodeComponent("frame28"),
    _2023NikeIncAllRightsReserved: makeNodeComponent(
      "_2023NikeIncAllRightsReserved"
    ),
    frame29: makeNodeComponent("frame29"),
    guides: makeNodeComponent("guides"),
    termsOfSale: makeNodeComponent("termsOfSale"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    nikePrivacyPolicy: makeNodeComponent("nikePrivacyPolicy"),
    autoLayoutVertical: makeNodeComponent("autoLayoutVertical"),
    frame30: makeNodeComponent("frame30"),
    autoLayoutVertical2: makeNodeComponent("autoLayoutVertical2"),
    autoLayoutVertical3: makeNodeComponent("autoLayoutVertical3"),
    frame31: makeNodeComponent("frame31"),
    autoLayoutHorizontal5: makeNodeComponent("autoLayoutHorizontal5"),
    frame32: makeNodeComponent("frame32"),
    autoLayoutHorizontal6: makeNodeComponent("autoLayoutHorizontal6"),
    autoLayoutHorizontal7: makeNodeComponent("autoLayoutHorizontal7"),
    price: makeNodeComponent("price"),
    autoLayoutHorizontal8: makeNodeComponent("autoLayoutHorizontal8"),
    addProduct: makeNodeComponent("addProduct"),
    addProductPage2: makeNodeComponent("addProductPage2"),
    // Metadata about props expected for PlasmicAddProducts
    internalVariantProps: PlasmicAddProducts__VariantProps,
    internalArgProps: PlasmicAddProducts__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAddProducts;
/* prettier-ignore-end */
