// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hGXuZyzubCg89KNadA76kG
// Component: C7st6MXL9g
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import Button from "../../Button"; // plasmic-import: AHmQZeuRNXKDJT/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_new_template_vendure.module.css"; // plasmic-import: hGXuZyzubCg89KNadA76kG/projectcss
import sty from "./PlasmicSuccessPayment.module.css"; // plasmic-import: C7st6MXL9g/css
import SearchIconIcon from "./icons/PlasmicIcon__SearchIcon"; // plasmic-import: D4yg-u7L-R/icon
import ChartIcon from "./icons/PlasmicIcon__Chart"; // plasmic-import: p2IhKl_G-k/icon
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: HKcCIpauuB9CGm/icon
import Frame2Icon from "./icons/PlasmicIcon__Frame2"; // plasmic-import: m4v5BuZET3af0x/icon
import Frame3Icon from "./icons/PlasmicIcon__Frame3"; // plasmic-import: gfo1RJd54zPXVx/icon
import Frame4Icon from "./icons/PlasmicIcon__Frame4"; // plasmic-import: OiKd2RcJwoXpl_/icon
import Frame5Icon from "./icons/PlasmicIcon__Frame5"; // plasmic-import: P2rc9Q1TWVaB44/icon
import Frame6Icon from "./icons/PlasmicIcon__Frame6"; // plasmic-import: Dd9xfOskzbTivN/icon
import Frame7Icon from "./icons/PlasmicIcon__Frame7"; // plasmic-import: p2GNwuTvHzmKNe/icon
import Frame8Icon from "./icons/PlasmicIcon__Frame8"; // plasmic-import: FNI9-QXSpX_HrN/icon
import Frame9Icon from "./icons/PlasmicIcon__Frame9"; // plasmic-import: zkSQt1vk-MZjmD/icon
import Frame10Icon from "./icons/PlasmicIcon__Frame10"; // plasmic-import: dkJYLT93Q85JOK/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: HxL6vvEArh/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: mH8n81u4jI/icon
import Ellipse13Icon from "./icons/PlasmicIcon__Ellipse13"; // plasmic-import: pdrbH7mvB9/icon
import Ellipse14Icon from "./icons/PlasmicIcon__Ellipse14"; // plasmic-import: EIlUn99Mie/icon
import Group18Icon from "./icons/PlasmicIcon__Group18"; // plasmic-import: bU0V-NrL1HH/icon

export const PlasmicSuccessPayment__VariantProps = new Array();

export const PlasmicSuccessPayment__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSuccessPayment__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <GraphqlFetcher
            data-plasmic-name={"graphQlFetcher"}
            data-plasmic-override={overrides.graphQlFetcher}
            className={classNames("__wab_instance", sty.graphQlFetcher)}
            dataName={"fetchedData"}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"POST"}
            noLayout={false}
            query={{
              query:
                "query MyQuery($name: String) {\n  characters(filter: {name: $name}) {\n    results {\n      name\n      species\n      image\n    }\n  }\n}\n",
              variables: { name: "Rick Sanchez" }
            }}
            url={"https://rickandmortyapi.com/graphql"}
            varOverrides={{}}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    data-plasmic-name={"successPayment"}
                    data-plasmic-override={overrides.successPayment}
                    className={classNames(projectcss.all, sty.successPayment)}
                  >
                    <div
                      data-plasmic-name={"header"}
                      data-plasmic-override={overrides.header}
                      className={classNames(projectcss.all, sty.header)}
                    >
                      {false ? (
                        <SearchIconIcon
                          className={classNames(projectcss.all, sty.svg__a5Km6)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <ChartIcon
                          className={classNames(projectcss.all, sty.svg__xe2ZD)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <ChartIcon
                          className={classNames(projectcss.all, sty.svg__pncDq)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        data-plasmic-name={"frame"}
                        data-plasmic-override={overrides.frame}
                        className={classNames(projectcss.all, sty.frame)}
                      >
                        <div
                          data-plasmic-name={"frame2"}
                          data-plasmic-override={overrides.frame2}
                          className={classNames(projectcss.all, sty.frame2)}
                        >
                          <div
                            data-plasmic-name={"frame3"}
                            data-plasmic-override={overrides.frame3}
                            className={classNames(projectcss.all, sty.frame3)}
                          >
                            <div
                              data-plasmic-name={"newFeatured"}
                              data-plasmic-override={overrides.newFeatured}
                              className={classNames(
                                projectcss.all,
                                sty.newFeatured
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___3IqYl
                                )}
                              >
                                {"New & Featured"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"men"}
                              data-plasmic-override={overrides.men}
                              className={classNames(projectcss.all, sty.men)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__dmHa
                                )}
                              >
                                {"Men"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"women"}
                              data-plasmic-override={overrides.women}
                              className={classNames(projectcss.all, sty.women)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__uz50U
                                )}
                              >
                                {"Women"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"kids"}
                              data-plasmic-override={overrides.kids}
                              className={classNames(projectcss.all, sty.kids)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ic3Ij
                                )}
                              >
                                {"Kids"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"sale"}
                              data-plasmic-override={overrides.sale}
                              className={classNames(projectcss.all, sty.sale)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__eDep6
                                )}
                              >
                                {"Sale"}
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"snkrs"}
                              data-plasmic-override={overrides.snkrs}
                              className={classNames(projectcss.all, sty.snkrs)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__hA8R
                                )}
                              >
                                {"SNKRS"}
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame4"}
                            data-plasmic-override={overrides.frame4}
                            className={classNames(projectcss.all, sty.frame4)}
                          >
                            <div
                              data-plasmic-name={"frame5"}
                              data-plasmic-override={overrides.frame5}
                              className={classNames(projectcss.all, sty.frame5)}
                            >
                              <div
                                data-plasmic-name={"frame6"}
                                data-plasmic-override={overrides.frame6}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame6
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame7"}
                                  data-plasmic-override={overrides.frame7}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame7
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame8"}
                                    data-plasmic-override={overrides.frame8}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame8
                                    )}
                                  >
                                    <div
                                      data-plasmic-name={"search"}
                                      data-plasmic-override={overrides.search}
                                      className={classNames(
                                        projectcss.all,
                                        sty.search
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__qDtY
                                        )}
                                      >
                                        {"Search"}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"autoLayoutHorizontal"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame9"}
                                    data-plasmic-override={overrides.frame9}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame9
                                    )}
                                  >
                                    <FrameIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__m9RNr
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                            <p.Stack
                              as={"div"}
                              data-plasmic-name={"autoLayoutHorizontal2"}
                              data-plasmic-override={
                                overrides.autoLayoutHorizontal2
                              }
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.autoLayoutHorizontal2
                              )}
                            >
                              <div
                                data-plasmic-name={"autoLayoutHorizontal3"}
                                data-plasmic-override={
                                  overrides.autoLayoutHorizontal3
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.autoLayoutHorizontal3
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame10"}
                                  data-plasmic-override={overrides.frame10}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame10
                                  )}
                                >
                                  <Frame2Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__bMnmJ
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"autoLayoutHorizontal4"}
                                data-plasmic-override={
                                  overrides.autoLayoutHorizontal4
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.autoLayoutHorizontal4
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame11"}
                                  data-plasmic-override={overrides.frame11}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame11
                                  )}
                                >
                                  <Frame3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__fix7L
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </p.Stack>
                            <div
                              data-plasmic-name={"frame12"}
                              data-plasmic-override={overrides.frame12}
                              className={classNames(
                                projectcss.all,
                                sty.frame12
                              )}
                            >
                              <Frame4Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___3M5G
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame13"}
                          data-plasmic-override={overrides.frame13}
                          className={classNames(projectcss.all, sty.frame13)}
                        >
                          <div
                            data-plasmic-name={"frame14"}
                            data-plasmic-override={overrides.frame14}
                            className={classNames(projectcss.all, sty.frame14)}
                          >
                            <Frame5Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__d0HoY
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"group12"}
                      data-plasmic-override={overrides.group12}
                      className={classNames(projectcss.all, sty.group12)}
                    >
                      <div
                        data-plasmic-name={"footer"}
                        data-plasmic-override={overrides.footer}
                        className={classNames(projectcss.all, sty.footer)}
                      >
                        <div
                          data-plasmic-name={"frame20"}
                          data-plasmic-override={overrides.frame20}
                          className={classNames(projectcss.all, sty.frame20)}
                        >
                          <div
                            data-plasmic-name={"frame21"}
                            data-plasmic-override={overrides.frame21}
                            className={classNames(projectcss.all, sty.frame21)}
                          >
                            <div
                              data-plasmic-name={"frame22"}
                              data-plasmic-override={overrides.frame22}
                              className={classNames(
                                projectcss.all,
                                sty.frame22
                              )}
                            >
                              <div
                                data-plasmic-name={"frame23"}
                                data-plasmic-override={overrides.frame23}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame23
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame24"}
                                  data-plasmic-override={overrides.frame24}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame24
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame25"}
                                    data-plasmic-override={overrides.frame25}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame25
                                    )}
                                  >
                                    <div
                                      data-plasmic-name={"findAStore"}
                                      data-plasmic-override={
                                        overrides.findAStore
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.findAStore
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__q49NH
                                        )}
                                      >
                                        {"Find A Store"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"becomeAMember"}
                                      data-plasmic-override={
                                        overrides.becomeAMember
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.becomeAMember
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__c9HTw
                                        )}
                                      >
                                        {"Become A Member"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"signUpForEmail"}
                                      data-plasmic-override={
                                        overrides.signUpForEmail
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.signUpForEmail
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__ufC34
                                        )}
                                      >
                                        {"Sign Up for Email"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"sendUsFeedback"}
                                      data-plasmic-override={
                                        overrides.sendUsFeedback
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.sendUsFeedback
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__hHe9L
                                        )}
                                      >
                                        {"Send Us Feedback"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"studentDiscounts"}
                                      data-plasmic-override={
                                        overrides.studentDiscounts
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.studentDiscounts
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__cvTdj
                                        )}
                                      >
                                        {"Student Discounts"}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"frame26"}
                                  data-plasmic-override={overrides.frame26}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame26
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame27"}
                                    data-plasmic-override={overrides.frame27}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame27
                                    )}
                                  >
                                    <div
                                      data-plasmic-name={"getHelp"}
                                      data-plasmic-override={overrides.getHelp}
                                      className={classNames(
                                        projectcss.all,
                                        sty.getHelp
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__h7EyA
                                        )}
                                      >
                                        {"Get Help"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"orderStatus"}
                                      data-plasmic-override={
                                        overrides.orderStatus
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.orderStatus
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__kiZjR
                                        )}
                                      >
                                        {"Order Status"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"delivery"}
                                      data-plasmic-override={overrides.delivery}
                                      className={classNames(
                                        projectcss.all,
                                        sty.delivery
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__xY182
                                        )}
                                      >
                                        {"Delivery"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"returns"}
                                      data-plasmic-override={overrides.returns}
                                      className={classNames(
                                        projectcss.all,
                                        sty.returns
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__q3Qc
                                        )}
                                      >
                                        {"Returns"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"paymentOptions"}
                                      data-plasmic-override={
                                        overrides.paymentOptions
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.paymentOptions
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__rhReF
                                        )}
                                      >
                                        {"Payment Options"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={
                                        "contactUsOnNikecomInquiries"
                                      }
                                      data-plasmic-override={
                                        overrides.contactUsOnNikecomInquiries
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.contactUsOnNikecomInquiries
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__y9Gfv
                                        )}
                                      >
                                        {"Contact Us On Nike.com Inquiries"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={
                                        "contactUsOnAllOtherInquiries"
                                      }
                                      data-plasmic-override={
                                        overrides.contactUsOnAllOtherInquiries
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.contactUsOnAllOtherInquiries
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__jiRcv
                                        )}
                                      >
                                        {"Contact Us On All Other Inquiries"}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"frame28"}
                                  data-plasmic-override={overrides.frame28}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame28
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame29"}
                                    data-plasmic-override={overrides.frame29}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame29
                                    )}
                                  >
                                    <div
                                      data-plasmic-name={"aboutNike"}
                                      data-plasmic-override={
                                        overrides.aboutNike
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.aboutNike
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__uguSf
                                        )}
                                      >
                                        {"About Nike"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"news"}
                                      data-plasmic-override={overrides.news}
                                      className={classNames(
                                        projectcss.all,
                                        sty.news
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__dgp9N
                                        )}
                                      >
                                        {"News"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"careers"}
                                      data-plasmic-override={overrides.careers}
                                      className={classNames(
                                        projectcss.all,
                                        sty.careers
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__ff1UI
                                        )}
                                      >
                                        {"Careers"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"investors"}
                                      data-plasmic-override={
                                        overrides.investors
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.investors
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text___5HRd6
                                        )}
                                      >
                                        {"Investors"}
                                      </div>
                                    </div>
                                    <div
                                      data-plasmic-name={"sustainability"}
                                      data-plasmic-override={
                                        overrides.sustainability
                                      }
                                      className={classNames(
                                        projectcss.all,
                                        sty.sustainability
                                      )}
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text___0CVmT
                                        )}
                                      >
                                        {"Sustainability"}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"frame30"}
                                data-plasmic-override={overrides.frame30}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame30
                                )}
                              >
                                <div
                                  data-plasmic-name={"frame31"}
                                  data-plasmic-override={overrides.frame31}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame31
                                  )}
                                >
                                  <Frame6Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__ssXra
                                    )}
                                    role={"img"}
                                  />
                                </div>
                                <div
                                  data-plasmic-name={"frame32"}
                                  data-plasmic-override={overrides.frame32}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame32
                                  )}
                                >
                                  <Frame7Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__wp3Rw
                                    )}
                                    role={"img"}
                                  />
                                </div>
                                <div
                                  data-plasmic-name={"frame33"}
                                  data-plasmic-override={overrides.frame33}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame33
                                  )}
                                >
                                  <Frame8Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___0JRfx
                                    )}
                                    role={"img"}
                                  />
                                </div>
                                <div
                                  data-plasmic-name={"frame15"}
                                  data-plasmic-override={overrides.frame15}
                                  className={classNames(
                                    projectcss.all,
                                    sty.frame15
                                  )}
                                >
                                  <Frame9Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__b5XoP
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"frame16"}
                              data-plasmic-override={overrides.frame16}
                              className={classNames(
                                projectcss.all,
                                sty.frame16
                              )}
                            >
                              <div
                                data-plasmic-name={"frame17"}
                                data-plasmic-override={overrides.frame17}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame17
                                )}
                              >
                                <p.Stack
                                  as={"div"}
                                  data-plasmic-name={"autoLayoutHorizontal5"}
                                  data-plasmic-override={
                                    overrides.autoLayoutHorizontal5
                                  }
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.autoLayoutHorizontal5
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"frame18"}
                                    data-plasmic-override={overrides.frame18}
                                    className={classNames(
                                      projectcss.all,
                                      sty.frame18
                                    )}
                                  >
                                    <Frame10Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__sZhny
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__oZxKf
                                    )}
                                  >
                                    {"India"}
                                  </div>
                                </p.Stack>
                                <div
                                  data-plasmic-name={
                                    "_2023NikeIncAllRightsReserved"
                                  }
                                  data-plasmic-override={
                                    overrides._2023NikeIncAllRightsReserved
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty._2023NikeIncAllRightsReserved
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__ntd2C
                                    )}
                                  >
                                    {"© 2023 Nike, Inc. All Rights Reserved"}
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"frame19"}
                                data-plasmic-override={overrides.frame19}
                                className={classNames(
                                  projectcss.all,
                                  sty.frame19
                                )}
                              >
                                <div
                                  data-plasmic-name={"guides"}
                                  data-plasmic-override={overrides.guides}
                                  className={classNames(
                                    projectcss.all,
                                    sty.guides
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__wqTo
                                    )}
                                  >
                                    {"Guides"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"termsOfSale"}
                                  data-plasmic-override={overrides.termsOfSale}
                                  className={classNames(
                                    projectcss.all,
                                    sty.termsOfSale
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__vzFB
                                    )}
                                  >
                                    {"Terms of Sale"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"termsOfUse"}
                                  data-plasmic-override={overrides.termsOfUse}
                                  className={classNames(
                                    projectcss.all,
                                    sty.termsOfUse
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___5Ve6C
                                    )}
                                  >
                                    {"Terms of Use"}
                                  </div>
                                </div>
                                <div
                                  data-plasmic-name={"nikePrivacyPolicy"}
                                  data-plasmic-override={
                                    overrides.nikePrivacyPolicy
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    sty.nikePrivacyPolicy
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__bmbk6
                                    )}
                                  >
                                    {"Nike Privacy Policy"}
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <Button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        link={`/homepage`}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___85YM
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <h5
                                data-plasmic-name={"h5"}
                                data-plasmic-override={overrides.h5}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h5,
                                  projectcss.__wab_text,
                                  sty.h5
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{
                                      fontWeight: 700,
                                      color: "#FFFFFF"
                                    }}
                                  >
                                    {"Continue Shopping!"}
                                  </span>
                                </React.Fragment>
                              </h5>
                            }

                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      </Button>
                    </div>
                    <div
                      data-plasmic-name={"rectangle18"}
                      data-plasmic-override={overrides.rectangle18}
                      className={classNames(projectcss.all, sty.rectangle18)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eXbUp
                        )}
                      >
                        {"$1.224.00"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qVq0Z
                        )}
                      >
                        {"Payment Time"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lusXu
                        )}
                      >
                        {"00007567362"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wFj9
                        )}
                      >
                        {"Ref Number"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xQczA
                        )}
                      >
                        {"Payment Successful!"}
                      </div>
                      <Vector6Icon
                        className={classNames(projectcss.all, sty.svg__wiKiK)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uIt2P
                        )}
                      >
                        {"Payment Methode"}
                      </div>
                      <Vector5Icon
                        className={classNames(projectcss.all, sty.svg__qzJnq)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pUqq
                        )}
                      >
                        {"Sender Name"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ozb6H
                        )}
                      >
                        {"Total Payment +\nAdmin Fee"}
                      </div>
                      <Ellipse13Icon
                        className={classNames(projectcss.all, sty.svg__qK9W)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h2N9L
                        )}
                      >
                        {"Falentino Agustino"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__e7N6J
                        )}
                      >
                        {"$1.224.00"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wt62M
                        )}
                      >
                        {"Credit Card"}
                      </div>
                      <Ellipse14Icon
                        className={classNames(projectcss.all, sty.svg__u4X4E)}
                        role={"img"}
                      />

                      <Group18Icon
                        className={classNames(projectcss.all, sty.svg__lM7Gb)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zOfMt
                        )}
                      >
                        {"09 -04-2023, 02.21 AM"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zyUvd
                      )}
                    >
                      {"Thank you for shopping, continue shopping?"}
                    </div>
                  </div>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphqlFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "graphQlFetcher",
    "freeBox",
    "successPayment",
    "header",
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "group12",
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "button",
    "h5",
    "rectangle18"
  ],

  graphQlFetcher: [
    "graphQlFetcher",
    "freeBox",
    "successPayment",
    "header",
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "group12",
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "button",
    "h5",
    "rectangle18"
  ],

  freeBox: [
    "freeBox",
    "successPayment",
    "header",
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "group12",
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "button",
    "h5",
    "rectangle18"
  ],

  successPayment: [
    "successPayment",
    "header",
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14",
    "group12",
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "button",
    "h5",
    "rectangle18"
  ],

  header: [
    "header",
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14"
  ],

  frame: [
    "frame",
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12",
    "frame13",
    "frame14"
  ],

  frame2: [
    "frame2",
    "frame3",
    "newFeatured",
    "men",
    "women",
    "kids",
    "sale",
    "snkrs",
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12"
  ],

  frame3: ["frame3", "newFeatured", "men", "women", "kids", "sale", "snkrs"],
  newFeatured: ["newFeatured"],
  men: ["men"],
  women: ["women"],
  kids: ["kids"],
  sale: ["sale"],
  snkrs: ["snkrs"],
  frame4: [
    "frame4",
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9",
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11",
    "frame12"
  ],

  frame5: [
    "frame5",
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9"
  ],

  frame6: [
    "frame6",
    "frame7",
    "frame8",
    "search",
    "autoLayoutHorizontal",
    "frame9"
  ],

  frame7: ["frame7", "frame8", "search"],
  frame8: ["frame8", "search"],
  search: ["search"],
  autoLayoutHorizontal: ["autoLayoutHorizontal", "frame9"],
  frame9: ["frame9"],
  autoLayoutHorizontal2: [
    "autoLayoutHorizontal2",
    "autoLayoutHorizontal3",
    "frame10",
    "autoLayoutHorizontal4",
    "frame11"
  ],

  autoLayoutHorizontal3: ["autoLayoutHorizontal3", "frame10"],
  frame10: ["frame10"],
  autoLayoutHorizontal4: ["autoLayoutHorizontal4", "frame11"],
  frame11: ["frame11"],
  frame12: ["frame12"],
  frame13: ["frame13", "frame14"],
  frame14: ["frame14"],
  group12: [
    "group12",
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy",
    "button",
    "h5"
  ],

  footer: [
    "footer",
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame20: [
    "frame20",
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame21: [
    "frame21",
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15",
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame22: [
    "frame22",
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "frame15"
  ],

  frame23: [
    "frame23",
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame24: [
    "frame24",
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  frame25: [
    "frame25",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  findAStore: ["findAStore"],
  becomeAMember: ["becomeAMember"],
  signUpForEmail: ["signUpForEmail"],
  sendUsFeedback: ["sendUsFeedback"],
  studentDiscounts: ["studentDiscounts"],
  frame26: [
    "frame26",
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  frame27: [
    "frame27",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  getHelp: ["getHelp"],
  orderStatus: ["orderStatus"],
  delivery: ["delivery"],
  returns: ["returns"],
  paymentOptions: ["paymentOptions"],
  contactUsOnNikecomInquiries: ["contactUsOnNikecomInquiries"],
  contactUsOnAllOtherInquiries: ["contactUsOnAllOtherInquiries"],
  frame28: [
    "frame28",
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame29: [
    "frame29",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  aboutNike: ["aboutNike"],
  news: ["news"],
  careers: ["careers"],
  investors: ["investors"],
  sustainability: ["sustainability"],
  frame30: ["frame30", "frame31", "frame32", "frame33", "frame15"],
  frame31: ["frame31"],
  frame32: ["frame32"],
  frame33: ["frame33"],
  frame15: ["frame15"],
  frame16: [
    "frame16",
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved",
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame17: [
    "frame17",
    "autoLayoutHorizontal5",
    "frame18",
    "_2023NikeIncAllRightsReserved"
  ],

  autoLayoutHorizontal5: ["autoLayoutHorizontal5", "frame18"],
  frame18: ["frame18"],
  _2023NikeIncAllRightsReserved: ["_2023NikeIncAllRightsReserved"],
  frame19: [
    "frame19",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  guides: ["guides"],
  termsOfSale: ["termsOfSale"],
  termsOfUse: ["termsOfUse"],
  nikePrivacyPolicy: ["nikePrivacyPolicy"],
  button: ["button", "h5"],
  h5: ["h5"],
  rectangle18: ["rectangle18"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSuccessPayment__ArgProps,
          internalVariantPropNames: PlasmicSuccessPayment__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSuccessPayment__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSuccessPayment";
  } else {
    func.displayName = `PlasmicSuccessPayment.${nodeName}`;
  }
  return func;
}

export const PlasmicSuccessPayment = Object.assign(
  // Top-level PlasmicSuccessPayment renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    successPayment: makeNodeComponent("successPayment"),
    header: makeNodeComponent("header"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    newFeatured: makeNodeComponent("newFeatured"),
    men: makeNodeComponent("men"),
    women: makeNodeComponent("women"),
    kids: makeNodeComponent("kids"),
    sale: makeNodeComponent("sale"),
    snkrs: makeNodeComponent("snkrs"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    frame8: makeNodeComponent("frame8"),
    search: makeNodeComponent("search"),
    autoLayoutHorizontal: makeNodeComponent("autoLayoutHorizontal"),
    frame9: makeNodeComponent("frame9"),
    autoLayoutHorizontal2: makeNodeComponent("autoLayoutHorizontal2"),
    autoLayoutHorizontal3: makeNodeComponent("autoLayoutHorizontal3"),
    frame10: makeNodeComponent("frame10"),
    autoLayoutHorizontal4: makeNodeComponent("autoLayoutHorizontal4"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    frame13: makeNodeComponent("frame13"),
    frame14: makeNodeComponent("frame14"),
    group12: makeNodeComponent("group12"),
    footer: makeNodeComponent("footer"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    frame22: makeNodeComponent("frame22"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    frame25: makeNodeComponent("frame25"),
    findAStore: makeNodeComponent("findAStore"),
    becomeAMember: makeNodeComponent("becomeAMember"),
    signUpForEmail: makeNodeComponent("signUpForEmail"),
    sendUsFeedback: makeNodeComponent("sendUsFeedback"),
    studentDiscounts: makeNodeComponent("studentDiscounts"),
    frame26: makeNodeComponent("frame26"),
    frame27: makeNodeComponent("frame27"),
    getHelp: makeNodeComponent("getHelp"),
    orderStatus: makeNodeComponent("orderStatus"),
    delivery: makeNodeComponent("delivery"),
    returns: makeNodeComponent("returns"),
    paymentOptions: makeNodeComponent("paymentOptions"),
    contactUsOnNikecomInquiries: makeNodeComponent(
      "contactUsOnNikecomInquiries"
    ),
    contactUsOnAllOtherInquiries: makeNodeComponent(
      "contactUsOnAllOtherInquiries"
    ),
    frame28: makeNodeComponent("frame28"),
    frame29: makeNodeComponent("frame29"),
    aboutNike: makeNodeComponent("aboutNike"),
    news: makeNodeComponent("news"),
    careers: makeNodeComponent("careers"),
    investors: makeNodeComponent("investors"),
    sustainability: makeNodeComponent("sustainability"),
    frame30: makeNodeComponent("frame30"),
    frame31: makeNodeComponent("frame31"),
    frame32: makeNodeComponent("frame32"),
    frame33: makeNodeComponent("frame33"),
    frame15: makeNodeComponent("frame15"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    autoLayoutHorizontal5: makeNodeComponent("autoLayoutHorizontal5"),
    frame18: makeNodeComponent("frame18"),
    _2023NikeIncAllRightsReserved: makeNodeComponent(
      "_2023NikeIncAllRightsReserved"
    ),
    frame19: makeNodeComponent("frame19"),
    guides: makeNodeComponent("guides"),
    termsOfSale: makeNodeComponent("termsOfSale"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    nikePrivacyPolicy: makeNodeComponent("nikePrivacyPolicy"),
    button: makeNodeComponent("button"),
    h5: makeNodeComponent("h5"),
    rectangle18: makeNodeComponent("rectangle18"),
    // Metadata about props expected for PlasmicSuccessPayment
    internalVariantProps: PlasmicSuccessPayment__VariantProps,
    internalArgProps: PlasmicSuccessPayment__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSuccessPayment;
/* prettier-ignore-end */
